import json
import os
import sys

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<a href=\"https://colab.research.google.com/\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>\n",
    "\n",
    "# AI Modul 3.3: Praktikum Sintaks Dasar Python\n",
    "### Aturan Leksikal dan Tokenisasi, Indentasi Signifikan (Off-Side Rule), Standar Rekayasa Kode Bersih PEP 8, Sistem Dokumentasi PEP 257, dan Pemodelan Neraca Air Lahan Sawit\n",
    "\n",
    "---\n",
    "\n",
    "> **Diktat Terkait:** [AI_Modul_3.3_Sintaks_Dasar_Python.md](../../docs/part-03/AI_Modul_3.3_Sintaks_Dasar_Python.md)  \n",
    "> **Outputs:** Skrip tokenisasi kode sumber via modul bawaan `tokenize`, modul kalkulasi neraca air berstandar PEP 8 & PEP 257, serta utilitas auditor kepatuhan sintaksis mandiri.  \n",
    "> **Outcomes:** Mahasiswa menguasai mekanisme tumpukan indentasi (*indent stack*), terampil menerapkan konvensi penamaan PEP 8, serta mampu merancang dokumentasi introspektif (*docstrings*).  \n",
    "> **Impacts:** Terciptanya basis kode kecerdasan buatan perkebunan yang bersih, mudah dipelihara (*maintainable*), bebas ambiguitas logika, dan berstandar rekayasa perangkat lunak internasional.\n",
    ">\n",
    "> **Tujuan Praktikum:**  \n",
    "> 1. Memeriksa daftar kata kunci resmi Python (`keyword.kwlist`) dan mengaudit keabsahan identifier.  \n",
    "> 2. Menganalisis aliran tokenisasi leksikal (`INDENT`, `DEDENT`, `NAME`, `OP`) menggunakan pustaka `tokenize`.  \n",
    "> 3. Memanfaatkan sistem introspeksi dokumentasi objek (`__doc__` dan `help()`).  \n",
    "> 4. Menjalankan model neraca air lahan perkebunan sawit (`KalkulatorNeracaAirSawit`) dan memvisualisasikan dinamikanya.  \n",
    "> 5. Menyelesaikan 3 tantangan mandiri: validasi identifier, generator statistik token, dan auditor kepatuhan PEP 8."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Persiapan Environment & Pemuatan Library\n",
    "Jalankan sel berikut untuk memuat pustaka standar pengurai token leksikal dan visualisasi grafik:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import io\n",
    "import keyword\n",
    "import tokenize\n",
    "import token\n",
    "import sys\n",
    "from dataclasses import dataclass\n",
    "from typing import Any, Dict, List, Optional, Tuple\n",
    "\n",
    "# Modul numerik & visualisasi\n",
    "import numpy as np\n",
    "import matplotlib\n",
    "matplotlib.use('Agg')\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Konfigurasi visualisasi grafik\n",
    "plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')\n",
    "plt.rcParams['figure.dpi'] = 120\n",
    "plt.rcParams['font.size'] = 10\n",
    "\n",
    "print(\"[OK] Seluruh pustaka dasar dan analitika berhasil diinisialisasi.\")\n",
    "print(f\"[INFO] Python Version : {sys.version.split()[0]}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Eksplorasi Struktur Leksikal & Kata Kunci Resmi Python\n",
    "Memeriksa kata kunci resmi (*reserved keywords*) dan menguji keabsahan penamaan identifier variabel."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "daftar_kw = keyword.kwlist\n",
    "print(\"=\" * 75)\n",
    "print(f\"DAFTAR KATA KUNCI RESMI PYTHON 3 (TOTAL: {len(daftar_kw)} KATA KUNCI)\")\n",
    "print(\"=\" * 75)\n",
    "\n",
    "# Tampilkan dalam format tabel 5 kolom\n",
    "for i in range(0, len(daftar_kw), 5):\n",
    "    baris = daftar_kw[i:i+5]\n",
    "    print(\"  \".join(f\"{kw:<12}\" for kw in baris))\n",
    "print(\"=\" * 75)\n",
    "\n",
    "# Pengujian Keabsahan Identifier\n",
    "sampel_nama = [\n",
    "    \"suhu_kanopi_c\",     # Sah (snake_case)\n",
    "    \"KalkulatorSawit\",   # Sah (PascalCase)\n",
    "    \"_kalibrasi_sensor\", # Sah (private attribute)\n",
    "    \"2_blok_kebun\",      # Tidak Sah (diawali angka)\n",
    "    \"kadar-air\",         # Tidak Sah (mengandung tanda minus / operator)\n",
    "    \"def\",               # Tidak Sah (kata kunci resmi)\n",
    "    \"yield\",             # Tidak Sah (kata kunci resmi)\n",
    "    \"hasil_panen_ton\"    # Sah\n",
    "]\n",
    "\n",
    "print(\"\\nUJI KEABSAHAN PENAMAAN IDENTIFIER:\")\n",
    "for nama in sampel_nama:\n",
    "    is_id = nama.isidentifier()\n",
    "    is_kw = keyword.iskeyword(nama)\n",
    "    valid = is_id and not is_kw\n",
    "    alasan = \"Sah (Valid)\" if valid else (\"Kata Kunci Resmi\" if is_kw else \"Karakter Tidak Sesuai\")\n",
    "    simbol = \"[V]\" if valid else \"[X]\"\n",
    "    print(f\" {simbol} {nama:<20} : {alasan}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Pembedahan Aliran Token & Tumpukan Indentasi (`tokenize`)\n",
    "Membongkar baris kode Python menjadi aliran token leksikal untuk melihat bagaimana CPython menghasilkan token `INDENT` dan `DEDENT`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Kode sumber target: Struktur percabangan kontrol irigasi kebun\n",
    "kode_uji = \"\"\"def evaluasi_tanah(rh: float):\n",
    "    if rh < 30.0:\n",
    "        irigasi_aktif = True\n",
    "    else:\n",
    "        irigasi_aktif = False\n",
    "    return irigasi_aktif\n",
    "\"\"\"\n",
    "\n",
    "print(\"=== PEMBEDAAN ALIRAN TOKEN (LEXICAL TOKENIZATION) ===\")\n",
    "print(f\"{'Tipe Token':<15} | {'String Teks Token':<20} | {'Rentang Baris & Kolom'}\")\n",
    "print(\"-\" * 65)\n",
    "\n",
    "stream_byte = io.BytesIO(kode_uji.encode('utf-8'))\n",
    "tokens = list(tokenize.tokenize(stream_byte.readline))\n",
    "\n",
    "for tok in tokens:\n",
    "    nama_tipe = token.tok_name.get(tok.type, str(tok.type))\n",
    "    # Tampilkan token utama saja untuk kejelasan\n",
    "    if nama_tipe in ['NAME', 'NUMBER', 'OP', 'INDENT', 'DEDENT', 'NEWLINE']:\n",
    "        nilai_teks = repr(tok.string)\n",
    "        posisi = f\"Baris {tok.start[0]}:{tok.start[1]} -> {tok.end[0]}:{tok.end[1]}\"\n",
    "        print(f\"{nama_tipe:<15} | {nilai_teks:<20} | {posisi}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Standarisasi Kode Bersih PEP 8 & Introspeksi Dokumentasi PEP 257\n",
    "Menampilkan dokumentasi formal fungsi secara dinamis melalui atribut `__doc__` bawaan CPython."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def hitung_evapotranspirasi_acuan(suhu_c: float, radiasi_mj: float) -> float:\n",
    "    \"\"\"Menghitung Evapotranspirasi Acuan (ETo) menggunakan metode FAO radiasi-suhu.\n",
    "\n",
    "    Formula empiris ini mengestimasi kehilangan air harian permukaan rumput acuan\n",
    "    untuk mendukung penjadwalan irigasi presisi perkebunan kelapa sawit.\n",
    "\n",
    "    Args:\n",
    "        suhu_c (float): Suhu udara harian rata-rata dalam derajat Celsius (> -10.0).\n",
    "        radiasi_mj (float): Radiasi matahari netto harian (MJ/m2/hari) (>= 0.0).\n",
    "\n",
    "    Returns:\n",
    "        float: Nilai ETo dalam milimeter per hari (mm/hari).\n",
    "\n",
    "    Raises:\n",
    "        ValueError: Jika radiasi bernilai negatif.\n",
    "    \"\"\"\n",
    "    if radiasi_mj < 0.0:\n",
    "        raise ValueError(f\"Radiasi matahari tidak boleh negatif: {radiasi_mj}\")\n",
    "    \n",
    "    eto = (0.408 * radiasi_mj) * (suhu_c / (suhu_c + 15.0) + 0.10) * 0.15\n",
    "    return max(1.0, round(eto, 2))\n",
    "\n",
    "print(\"=== INTROSPEKSI DOKUMENTASI FORMAL (PEP 257) ===\")\n",
    "print(f\"Nama Fungsi : {hitung_evapotranspirasi_acuan.__name__}\")\n",
    "print(\"Isi Docstring Resmi (__doc__):\\n\")\n",
    "print(hitung_evapotranspirasi_acuan.__doc__)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Implementasi Terpadu: Pipeline Pemodelan Neraca Air Lahan Sawit\n",
    "Mengeksekusi model simulasi neraca air tanah harian berbasis kelas `KalkulatorNeracaAirSawit` dan memvisualisasikan dinamika kadar air perakaran selama 5 hari berturut-turut."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Konstanta Fisik Tanah & Tanaman Sawit Dewasa (PEP 8 UPPER_CASE)\n",
    "KAPASITAS_LAPANG_MM: float = 180.0\n",
    "TITIK_LAYU_PERMANEN_MM: float = 65.0\n",
    "AIR_TERSEDIA_MAKSIMUM_MM: float = KAPASITAS_LAPANG_MM - TITIK_LAYU_PERMANEN_MM\n",
    "FRAKSI_DEPLESI_P: float = 0.50\n",
    "\n",
    "@dataclass(frozen=True)\n",
    "class KondisiAgroklimatHarian:\n",
    "    \"\"\"Parameter cuaca harian stasiun meteorologi kebun.\"\"\"\n",
    "    tanggal: str\n",
    "    suhu_c: float\n",
    "    kecepatan_angin_ms: float\n",
    "    radiasi_netto_mj: float\n",
    "    curah_hujan_mm: float\n",
    "\n",
    "\n",
    "class KalkulatorNeracaAirSawit:\n",
    "    \"\"\"Mesin simulasi neraca air perakaran kelapa sawit.\"\"\"\n",
    "    def __init__(self, kode_blok: str, luas_hektar: float, kc: float = 1.10) -> None:\n",
    "        if luas_hektar <= 0.0:\n",
    "            raise ValueError(\"Luas hektar harus positif.\")\n",
    "        self.kode_blok = kode_blok.strip().upper()\n",
    "        self.luas_hektar = luas_hektar\n",
    "        self.kc = kc\n",
    "        self._kadar_air_mm = KAPASITAS_LAPANG_MM\n",
    "\n",
    "    def hitung_neraca(self, iklim: KondisiAgroklimatHarian) -> Dict[str, Any]:\n",
    "        eto = (0.408 * iklim.radiasi_netto_mj) * (iklim.suhu_c / (iklim.suhu_c + 15.0) + 0.10) * 0.15\n",
    "        eto = max(1.5, min(7.5, round(eto, 2)))\n",
    "        etc = round(eto * self.kc, 2)\n",
    "        \n",
    "        hujan_efektif = round(iklim.curah_hujan_mm * 0.80, 2)\n",
    "        kadar_baru = self._kadar_air_mm + hujan_efektif - etc\n",
    "        self._kadar_air_mm = max(TITIK_LAYU_PERMANEN_MM, min(KAPASITAS_LAPANG_MM, round(kadar_baru, 2)))\n",
    "        \n",
    "        air_tersedia = max(0.0, self._kadar_air_mm - TITIK_LAYU_PERMANEN_MM)\n",
    "        ambang_cekaman = AIR_TERSEDIA_MAKSIMUM_MM * (1.0 - FRAKSI_DEPLESI_P)\n",
    "        stres = air_tersedia < ambang_cekaman\n",
    "        \n",
    "        defisit = round(KAPASITAS_LAPANG_MM - self._kadar_air_mm, 2) if stres else 0.0\n",
    "        volume_m3 = round(defisit * 10.0 * self.luas_hektar, 2)\n",
    "        \n",
    "        return {\n",
    "            \"tanggal\": iklim.tanggal,\n",
    "            \"eto\": eto,\n",
    "            \"etc\": etc,\n",
    "            \"kadar_air\": self._kadar_air_mm,\n",
    "            \"stres\": stres,\n",
    "            \"rekomendasi_m3\": volume_m3\n",
    "        }\n",
    "\n",
    "# Dataset simulasi 5 hari pengamatan\ndata_cuaca = [\n",
    "    KondisiAgroklimatHarian(\"Hari-1\", 28.0, 1.5, 18.0, 0.0),\n",
    "    KondisiAgroklimatHarian(\"Hari-2\", 29.5, 2.1, 22.0, 0.0),\n",
    "    KondisiAgroklimatHarian(\"Hari-3\", 30.0, 2.4, 23.5, 0.0),\n",
    "    KondisiAgroklimatHarian(\"Hari-4\", 30.5, 2.5, 24.0, 0.0),\n",
    "    KondisiAgroklimatHarian(\"Hari-5\", 26.0, 1.0, 12.0, 40.0), # Hujan deras\n",
    "]\n",
    "\n",
    "kalkulator = KalkulatorNeracaAirSawit(\"BLOK-A01\", luas_hektar=25.0)\n",
    "riwayat_simulasi = [kalkulator.hitung_neraca(hari) for hari in data_cuaca]\n",
    "\n",
    "print(\"=== HASIL SIMULASI NERACA AIR LAHAN KELAPA SAWIT ===\")\n",
    "for r in riwayat_simulasi:\n",
    "    st = \"[CEKAMAN AIR]\" if r[\"stres\"] else \"[AMAN]\"\n",
    "    print(f\"{r['tanggal']}: Kadar Air: {r['kadar_air']} mm | ETc: {r['etc']} mm | Status: {st} | Rekomendasi: {r['rekomendasi_m3']} m3\")\n",
    "\n",
    "# Visualisasi Grafik Neraca Air\nhari_label = [r[\"tanggal\"] for r in riwayat_simulasi]\nkadar_list = [r[\"kadar_air\"] for r in riwayat_simulasi]\n\nfig, ax = plt.subplots(figsize=(8, 4.2))\nax.plot(hari_label, kadar_list, marker='o', lw=2.2, color='royalblue', label='Kadar Air Aktual (mm)')\nax.axhline(KAPASITAS_LAPANG_MM, color='forestgreen', linestyle='--', label='Kapasitas Lapang (180 mm)')\nax.axhline(TITIK_LAYU_PERMANEN_MM + (AIR_TERSEDIA_MAKSIMUM_MM*0.5), color='darkorange', linestyle=':', label='Batas Kritis Cekaman (122.5 mm)')\nax.axhline(TITIK_LAYU_PERMANEN_MM, color='indianred', linestyle='--', label='Titik Layu Permanen (65 mm)')\n\nax.set_ylabel('Kadar Air Tanah (mm)', fontweight='bold')\nax.set_title('Dinamika Neraca Air Zona Perakaran Sawit (Metode FAO-56)', fontweight='bold', fontsize=11)\nax.legend(loc='lower left', frameon=True, fontsize=8.5)\nplt.tight_layout()\nplt.savefig('docs/assets/simulasi_neraca_air_sawit.png', dpi=150)\nprint(\"\\n[INFO] Grafik neraca air berhasil disimpan ke 'docs/assets/simulasi_neraca_air_sawit.png'.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Solusi Lengkap Tantangan Pemrograman Berjenjang\n",
    "Berikut adalah implementasi komprehensif dari ketiga tantangan mandiri yang terdapat pada diktat perkuliahan:"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Tantangan 1 (Tingkat Dasar): Pemeriksa Keabsahan Identifier Python\n",
    "Membangun fungsi `validasi_identifier_python` untuk mengevaluasi apakah suatu nama fitur sah digunakan sebagai variabel Python."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def validasi_identifier_python(nama_variabel: str) -> Dict[str, Any]:\n",
    "    \"\"\"\n",
    "    Memvalidasi apakah nama_variabel memenuhi kaidah identifier legal pada Python.\n",
    "    \"\"\"\n",
    "    if not isinstance(nama_variabel, str):\n",
    "        return {\"nama\": str(nama_variabel), \"is_valid\": False, \"alasan\": \"Input bukan string.\"}\n",
    "    \n",
    "    if keyword.iskeyword(nama_variabel):\n",
    "        return {\"nama\": nama_variabel, \"is_valid\": False, \"alasan\": \"Merupakan kata kunci resmi (Reserved Keyword).\"}\n",
    "        \n",
    "    if not nama_variabel.isidentifier():\n",
    "        if nama_variabel and nama_variabel[0].isdigit():\n",
    "            alasan = \"Identifier tidak boleh diawali oleh angka.\"\n",
    "        else:\n",
    "            alasan = \"Mengandung karakter khusus ilegal atau spasi.\"\n",
    "        return {\"nama\": nama_variabel, \"is_valid\": False, \"alasan\": alasan}\n",
    "        \n",
    "    return {\"nama\": nama_variabel, \"is_valid\": True, \"alasan\": \"Identifier sah dan valid.\"}\n",
    "\n",
    "# Pengujian Tantangan 1\n",
    "uji_identifier = [\"curah_hujan_harian\", \"1_sensor_tanah\", \"def\", \"kelembaban%\", \"_ndvi_kanopi\"]\n",
    "print(\"=== TANTANGAN 1: VALIDASI IDENTIFIER PYTHON ===\")\n",
    "for u in uji_identifier:\n",
    "    hasil = validasi_identifier_python(u)\n",
    "    status = \"[V] SAH\" if hasil[\"is_valid\"] else \"[X] GAGAL\"\n",
    "    print(f\"{status:<10} | {hasil['nama']:<20} : {hasil['alasan']}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Tantangan 2 (Tingkat Menengah): Penganalisis Aliran Token Kode Sumber via Modul `tokenize`\n",
    "Mengekstraksi dan menghitung distribusi frekuensi token leksikal pada sepotong kode program Python."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def analisis_aliran_token(potongan_kode: str) -> Dict[str, Any]:\n",
    "    \"\"\"\n",
    "    Mengekstraksi token leksikal dan menghitung distribusi frekuensi opcodenya.\n",
    "    \"\"\"\n",
    "    stream_byte = io.BytesIO(potongan_kode.encode('utf-8'))\n",
    "    frekuensi_token: Dict[str, int] = {}\n",
    "    total_token = 0\n",
    "    \n",
    "    for tok in tokenize.tokenize(stream_byte.readline):\n",
    "        nama_tipe = token.tok_name.get(tok.type, str(tok.type))\n",
    "        if nama_tipe not in ['ENCODING', 'ENDMARKER']:\n",
    "            frekuensi_token[nama_tipe] = frekuensi_token.get(nama_tipe, 0) + 1\n",
    "            total_token += 1\n",
    "            \n",
    "    return {\n",
    "        \"total_token\": total_token,\n",
    "        \"distribusi_token\": frekuensi_token\n",
    "    }\n",
    "\n",
    "# Pengujian Tantangan 2\n",
    "skrip_agrikultur = \"\"\"\n",
    "for hari in range(1, 8):\n",
    "    debit = luas * 15.5\n",
    "    if debit > 100.0:\n",
    "        print('Peringatan: Debit Berlebih')\n",
    "\"\"\"\n",
    "\n",
    "hasil_tok = analisis_aliran_token(skrip_agrikultur)\n",
    "print(\"=== TANTANGAN 2: STATISTIK DISTRIBUSI TOKEN ===\")\n",
    "print(f\"Total Token Leksikal : {hasil_tok['total_token']}\")\n",
    "for t_nama, t_count in sorted(hasil_tok[\"distribusi_token\"].items()):\n",
    "    print(f\" * {t_nama:<12} : {t_count} kemunculan\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Tantangan 3 (Tingkat Mahir): Auditor Kepatuhan Sintaksis PEP 8 Sederhana (*Linter Checker*)\n",
    "Membangun kelas `AuditorSintaksPEP8` untuk mendeteksi pelanggaran batas panjang baris (79 karakter), spasi trailing, dan tabulasi ilegal."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class AuditorSintaksPEP8:\n",
    "    \"\"\"\n",
    "    Linter sederhana untuk mengevaluasi kepatuhan kode Python terhadap aturan format PEP 8.\n",
    "    \"\"\"\n",
    "    def __init__(self, batas_panjang_baris: int = 79) -> None:\n",
    "        self.batas_panjang = batas_panjang_baris\n",
    "\n",
    "    def audit_kode(self, kode_sumber: str) -> Dict[str, Any]:\n",
    "        baris_list = kode_sumber.splitlines()\n",
    "        total_baris = len(baris_list)\n",
    "        pelanggaran_panjang: List[Tuple[int, int]] = []\n",
    "        pelanggaran_tab: List[int] = []\n",
    "        pelanggaran_trailing_spasi: List[int] = []\n",
    "        \n",
    "        for idx, baris in enumerate(baris_list, start=1):\n",
    "            # 1. Batas Panjang Baris\n",
    "            if len(baris) > self.batas_panjang:\n",
    "                pelanggaran_panjang.append((idx, len(baris)))\n",
    "            \n",
    "            # 2. Leading Tab\n",
    "            if baris.startswith(\"\\t\") or \"\\t\" in baris[:len(baris) - len(baris.lstrip())]:\n",
    "                pelanggaran_tab.append(idx)\n",
    "                \n",
    "            # 3. Trailing Whitespace di ujung baris\n",
    "            if baris.endswith(\" \") or baris.endswith(\"\\t\"):\n",
    "                pelanggaran_trailing_spasi.append(idx)\n",
    "                \n",
    "        total_pelanggaran = len(pelanggaran_panjang) + len(pelanggaran_tab) + len(pelanggaran_trailing_spasi)\n",
    "        # Skor kepatuhan proporsional\n",
    "        skor = max(0.0, round((1.0 - (total_pelanggaran / max(1, total_baris))) * 100.0, 1))\n",
    "        \n",
    "        return {\n",
    "            \"total_baris\": total_baris,\n",
    "            \"baris_melebihi_batas\": pelanggaran_panjang,\n",
    "            \"baris_memuat_tab\": pelanggaran_tab,\n",
    "            \"baris_trailing_spasi\": pelanggaran_trailing_spasi,\n",
    "            \"total_pelanggaran\": total_pelanggaran,\n",
    "            \"skor_kepatuhan_persen\": skor\n",
    "        }\n",
    "\n",
    "# Pengujian Tantangan 3\n",
    "kode_tugas_mahasiswa = \"\"\"def fungsi_pengolahan_sensor_pertanian_presisi_kelapa_sawit_yang_sangat_panjang_sekali():\n",
    "\tsuhu = 32.5  \n",
    "    if suhu > 30.0:\n",
    "        print('Kondisi Ekstrem')\n",
    "    return suhu\n",
    "\"\"\"\n",
    "\n",
    "auditor = AuditorSintaksPEP8(batas_panjang_baris=79)\n",
    "laporan_pep8 = auditor.audit_kode(kode_tugas_mahasiswa)\n",
    "\n",
    "print(\"=== TANTANGAN 3: AUDITOR KEPATUHAN PEP 8 ===\")\n",
    "print(f\"Skor Kepatuhan Kode : {laporan_pep8['skor_kepatuhan_persen']}%\")\n",
    "print(f\"Pelanggaran Panjang : {laporan_pep8['baris_melebihi_batas']} (Baris, Karakter)\")\n",
    "print(f\"Pelanggaran Tab     : Baris {laporan_pep8['baris_memuat_tab']}\")\n",
    "print(f\"Trailing Spasi Kosong: Baris {laporan_pep8['baris_trailing_spasi']}\")"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

output_path = "notebooks/part-03/AI_Modul_3.3_Praktikum_Sintaks_Dasar_Python.ipynb"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"[BERHASIL] File Jupyter Notebook tersimpan di: {output_path}")
