import json
import os

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<a href=\"https://colab.research.google.com/\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>\n",
    "\n",
    "# AI Modul 2.6: Praktikum Percabangan (if-else)\n",
    "### Pengendalian Alur Eksekusi, Refaktorisasi Guard Clauses, dan Pipeline Klasifikasi Mutu TBS Kelapa Sawit\n",
    "\n",
    "---\n",
    "\n",
    "> **Outputs:** Script implementasi struktur percabangan bersih (PEP 8), modul evaluasi pohon keputusan sortasi mutu TBS sawit, dan pola klausa penjaga (*guard clauses / early return pattern*).  \n",
    "> **Outcomes:** Mahasiswa terampil merancang alur logika percabangan tanpa struktur bersarang berlebih (*deeply nested conditionals*), menerjemahkan matriks kriteria agronomis pabrik kelapa sawit ke kode deterministik, dan memangkas kompleksitas siklomatis.  \n",
    "> **Impacts:** Mendukung otomasi stasiun penerimaan buah (*loading ramp*) di PKS modern, mencegah penurunan rendemen CPO akibat kontaminasi buah mentah/busuk, dan meningkatkan efisiensi komputasi sistem cerdas pertanian.\n",
    ">\n",
    "> **Tujuan Praktikum:**  \n",
    "> 1. Mempraktikkan sintaksis percabangan `if`, `if-else`, `if-elif-else`, dan operator ternary.  \n",
    "> 2. Mengidentifikasi kelemahan *nested conditionals* dan merefaktorisasi kode menggunakan *guard clauses*.  \n",
    "> 3. Membangun engine sortasi tandan buah segar (TBS) sawit berbasis pohon keputusan multi-kondisi.  \n",
    "> 4. Menyelesaikan tantangan berjenjang: evaluasi tekanan sterilizer, deteksi kematangan HSV, dan triage darurat PKS multi-sensor."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Persiapan Environment & Pemuatan Library\n",
    "Jalankan sel berikut untuk memuat pustaka matematika, enumerasi, dataclass, dan visualisasi grafik:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Mengimpor modul bawaan Python\n",
    "import math\n",
    "import sys\n",
    "import time\n",
    "import enum\n",
    "from dataclasses import dataclass\n",
    "from typing import List, Tuple, Dict, Any, Optional\n",
    "\n",
    "# Mengimpor pustaka numerik dan visualisasi\n",
    "import numpy as np\n",
    "import matplotlib\n",
    "matplotlib.use('Agg')\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Konfigurasi gaya visualisasi grafik\n",
    "plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')\n",
    "plt.rcParams['figure.dpi'] = 120\n",
    "plt.rcParams['font.size'] = 10\n",
    "\n",
    "print(\"[OK] Seluruh pustaka berhasil diinisialisasi.\")\n",
    "print(f\"[INFO] Versi Python Aktif: {sys.version.split()[0]}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Eksperimen Percabangan Dasar & Operator Ternary\n",
    "Mengevaluasi kondisi batas menggunakan percabangan tunggal, biner, multi-cabang, dan operator ternary satu baris."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. Percabangan Tunggal (if)\n",
    "suhu_sterilizer = 145.2  # Derajat Celcius\n",
    "if suhu_sterilizer > 140.0:\n",
    "    print(f\"[PERINGATAN] Suhu bejana {suhu_sterilizer} C melebihi batas keselamatan normal!\")\n",
    "\n",
    "# 2. Percabangan Biner (if-else)\n",
    "berat_tandan = 4.2  # kg\n",
    "if berat_tandan >= 5.0:\n",
    "    kategori_berat = \"LAYAK_OLAH\"\n",
    "else:\n",
    "    kategori_berat = \"AFKIR_UNDERWEIGHT\"\n",
    "print(f\"Tandan ({berat_tandan} kg) -> Status: {kategori_berat}\")\n",
    "\n",
    "# 3. Percabangan Multi-Kondisi (if-elif-else)\n",
    "brondol_lepas_persen = 45.0\n",
    "if brondol_lepas_persen < 12.0:\n",
    "    fraksi = \"FRAKSI 1 (MENTAH)\"\n",
    "elif brondol_lepas_persen <= 75.0:\n",
    "    fraksi = \"FRAKSI 2 (MATANG SEMPURNA)\"\n",
    "else:\n",
    "    fraksi = \"FRAKSI 3 (LEWAT MATANG / OVERRIPE)\"\n",
    "print(f\"Brondolan ({brondol_lepas_persen}%) -> Kategori: {fraksi}\")\n",
    "\n",
    "# 4. Operator Ternary (Conditional Expression)\n",
    "kelembaban_rh = 88.5\n",
    "status_kipas = \"KECEPATAN TINGGI\" if kelembaban_rh > 80.0 else \"HEMAT ENERGI\"\n",
    "print(f\"Sensor RH ({kelembaban_rh}%) -> Mode Kipas: {status_kipas}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Komparasi: Percabangan Bersarang Berlebih vs Klausa Penjaga (Guard Clauses)\n",
    "Membandingkan struktur kontrol bertingkat (*deeply nested conditionals*) dengan pola *Guard Clauses* yang linear dan bersih."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Implementasi A: Percabangan Bersarang Berlebih (Deeply Nested If-Else)\n",
    "def validasi_lori_nested(id_lori: Optional[str], muatan_ton: float, status_rem: str) -> str:\n",
    "    if id_lori is not None:\n",
    "        if muatan_ton > 0.0:\n",
    "            if muatan_ton <= 5.0:\n",
    "                if status_rem == \"AKTIF\":\n",
    "                    return \"LORI SIAP MASUK STERILIZER\"\n",
    "                else:\n",
    "                    return \"BAHAYA: REM TIDAK AKTIF\"\n",
    "            else:\n",
    "                return \"KELEBIHAN MUATAN\"\n",
    "        else:\n",
    "            return \"MUATAN KOSONG\"\n",
    "    else:\n",
    "        return \"ID LORI TIDAK VALID\"\n",
    "\n",
    "# Implementasi B: Pola Klausa Penjaga (Guard Clauses / Early Return)\n",
    "def validasi_lori_guard(id_lori: Optional[str], muatan_ton: float, status_rem: str) -> str:\n",
    "    if id_lori is None:\n",
    "        return \"ID LORI TIDAK VALID\"\n",
    "    if muatan_ton <= 0.0:\n",
    "        return \"MUATAN KOSONG\"\n",
    "    if muatan_ton > 5.0:\n",
    "        return \"KELEBIHAN MUATAN\"\n",
    "    if status_rem != \"AKTIF\":\n",
    "        return \"BAHAYA: REM TIDAK AKTIF\"\n",
    "    \n",
    "    # Alur Eksekusi Baku (Nominal Execution Path) tanpa lekukan!\n",
    "    return \"LORI SIAP MASUK STERILIZER\"\n",
    "\n",
    "# Pengujian Komparasi Keduanya\n",
    "kasus_uji = [\n",
    "    (None, 3.5, \"AKTIF\"),\n",
    "    (\"LORI-01\", -1.0, \"AKTIF\"),\n",
    "    (\"LORI-02\", 6.2, \"AKTIF\"),\n",
    "    (\"LORI-03\", 4.0, \"RUSAK\"),\n",
    "    (\"LORI-04\", 4.5, \"AKTIF\"),\n",
    "]\n",
    "\n",
    "print(\"=== KOMPARASI HASIL VALIDASI LORI PKS ===\")\n",
    "for lid, muatan, rem in kasus_uji:\n",
    "    res_a = validasi_lori_nested(lid, muatan, rem)\n",
    "    res_b = validasi_lori_guard(lid, muatan, rem)\n",
    "    assert res_a == res_b, \"Hasil tidak identik!\"\n",
    "    print(f\"Lori: {str(lid):<10} | Berat: {muatan:>4.1f}t | Rem: {rem:<6} -> Keputusan: {res_b}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Pipeline Klasifikasi Mutu TBS Sawit Berbasis Pohon Keputusan\n",
    "Menerapkan engine sortasi loading ramp PKS lengkap dengan pemodelan dataclass, enum, dan visualisasi distribusi batch."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class KategoriMutuTBS(enum.Enum):\n",
    "    PRIMA_EKSPOR_GRADE_A = \"PRIMA EKSPOR (GRADE A)\"\n",
    "    MENTAH_FRAKSI_1      = \"MENTAH (FRAKSI 1)\"\n",
    "    LEWAT_MATANG_FRAKSI_3 = \"LEWAT MATANG (FRAKSI 3)\"\n",
    "    TANGKAI_PANJANG      = \"TANGKAI PANJANG (>2.5cm)\"\n",
    "    KOTOR_SAMPAH_TINGGI  = \"KONTAMINASI TINGGI (>1.5%)\"\n",
    "    AFKIR_UNDERWEIGHT    = \"AFKIR UNDERWEIGHT (<5kg)\"\n",
    "\n",
    "@dataclass(frozen=True)\n",
    "class TelemetriTBS:\n",
    "    id_tandan: str\n",
    "    berat_kg: float\n",
    "    persen_brondol_lepas: float\n",
    "    panjang_tangkai_cm: float\n",
    "    kadar_kotoran_persen: float\n",
    "\n",
    "class EngineSortasiTBS:\n",
    "    BERAT_MINIMUM_KG: float = 5.0\n",
    "    BRONDOL_MIN_MATANG: float = 12.0\n",
    "    BRONDOL_MAX_MATANG: float = 75.0\n",
    "    PANJANG_TANGKAI_MAKS_CM: float = 2.5\n",
    "    KADAR_KOTORAN_MAKS_PERSEN: float = 1.5\n",
    "\n",
    "    @classmethod\n",
    "    def evaluasi_mutu(cls, tbs: TelemetriTBS) -> Tuple[KategoriMutuTBS, str]:\n",
    "        if tbs.berat_kg < cls.BERAT_MINIMUM_KG:\n",
    "            return KategoriMutuTBS.AFKIR_UNDERWEIGHT, f\"Berat {tbs.berat_kg}kg < {cls.BERAT_MINIMUM_KG}kg (Buah Pasir).\"\n",
    "        if tbs.persen_brondol_lepas < cls.BRONDOL_MIN_MATANG:\n",
    "            return KategoriMutuTBS.MENTAH_FRAKSI_1, f\"Brondol {tbs.persen_brondol_lepas}% < {cls.BRONDOL_MIN_MATANG}%.\"\n",
    "        if tbs.persen_brondol_lepas > cls.BRONDOL_MAX_MATANG:\n",
    "            return KategoriMutuTBS.LEWAT_MATANG_FRAKSI_3, f\"Brondol {tbs.persen_brondol_lepas}% > {cls.BRONDOL_MAX_MATANG}% (FFA tinggi).\"\n",
    "        if tbs.panjang_tangkai_cm > cls.PANJANG_TANGKAI_MAKS_CM:\n",
    "            return KategoriMutuTBS.TANGKAI_PANJANG, f\"Tangkai {tbs.panjang_tangkai_cm}cm > {cls.PANJANG_TANGKAI_MAKS_CM}cm.\"\n",
    "        if tbs.kadar_kotoran_persen > cls.KADAR_KOTORAN_MAKS_PERSEN:\n",
    "            return KategoriMutuTBS.KOTOR_SAMPAH_TINGGI, f\"Kotoran {tbs.kadar_kotoran_persen}% > {cls.KADAR_KOTORAN_MAKS_PERSEN}%.\"\n",
    "        \n",
    "        return KategoriMutuTBS.PRIMA_EKSPOR_GRADE_A, \"Memenuhi standar mutu prima CPO (> 23%).\"\n",
    "\n",
    "# Simulasi Data Batch Tandan Buah Segar\n",
    "kumpulan_tbs = [\n",
    "    TelemetriTBS(\"TBS-01\", 3.5, 25.0, 1.5, 0.4),\n",
    "    TelemetriTBS(\"TBS-02\", 16.0, 5.0, 2.0, 0.8),\n",
    "    TelemetriTBS(\"TBS-03\", 22.5, 82.0, 1.8, 0.5),\n",
    "    TelemetriTBS(\"TBS-04\", 18.0, 30.0, 4.5, 0.6),\n",
    "    TelemetriTBS(\"TBS-05\", 21.0, 45.0, 1.2, 3.5),\n",
    "    TelemetriTBS(\"TBS-06\", 19.5, 35.0, 1.5, 0.5),\n",
    "    TelemetriTBS(\"TBS-07\", 25.0, 50.0, 2.0, 0.4),\n",
    "    TelemetriTBS(\"TBS-08\", 17.5, 40.0, 1.8, 0.3),\n",
    "]\n",
    "\n",
    "distribusi_kategori: Dict[str, int] = {}\n",
    "for item in kumpulan_tbs:\n",
    "    kat, alasan = EngineSortasiTBS.evaluasi_mutu(item)\n",
    "    distribusi_kategori[kat.value] = distribusi_kategori.get(kat.value, 0) + 1\n",
    "\n",
    "print(\"=== HASIL AUDIT SORTASI TBS LOADING RAMP ===\")\n",
    "for k, v in distribusi_kategori.items():\n",
    "    print(f\"{k:<35}: {v} Tandan\")\n",
    "\n",
    "# Visualisasi Bar Chart Distribusi Mutu TBS\n",
    "plt.figure(figsize=(10, 5))\n",
    "labels = list(distribusi_kategori.keys())\n",
    "counts = list(distribusi_kategori.values())\n",
    "colors = ['#15803D' if 'PRIMA' in l else '#DC2626' if 'AFKIR' in l else '#D97706' for l in labels]\n",
    "\n",
    "bars = plt.barh(labels, counts, color=colors, edgecolor='black', alpha=0.85)\n",
    "plt.xlabel('Jumlah Tandan (Unit)', fontweight='bold')\n",
    "plt.title('Distribusi Klasifikasi Mutu Tandan Buah Segar (TBS) di PKS', fontweight='bold', fontsize=12)\n",
    "plt.xlim(0, max(counts) + 1.5)\n",
    "for bar in bars:\n",
    "    w = bar.get_width()\n",
    "    plt.text(w + 0.1, bar.get_y() + bar.get_height()/2, str(int(w)), va='center', fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig('docs/assets/distribusi_sortasi_tbs_loading_ramp.png', dpi=150)\n",
    "print(\"[INFO] Grafik distribusi mutu TBS berhasil disimpan ke 'docs/assets/distribusi_sortasi_tbs_loading_ramp.png'.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Solusi Tantangan Mandiri (Scaffolded Challenges)\n",
    "Implementasi komprehensif untuk ketiga tantangan praktikum berjenjang."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# === TANTANGAN 1: KLASIFIKASI ZONA TEKANAN UAP STERILIZER ===\n",
    "def evaluasi_tekanan_sterilizer(tekanan_bar: float) -> str:\n",
    "    \"\"\"\n",
    "    Mengklasifikasikan status operasional bejana uap perebusan sawit.\n",
    "    Dilengkapi dengan Guard Clause untuk menangani nilai pembacaan sensor negatif.\n",
    "    \"\"\"\n",
    "    if tekanan_bar < 0.0:\n",
    "        return \"ERROR: ANOMALI SENSOR (TEKANAN NEGATIF)\"\n",
    "        \n",
    "    if tekanan_bar < 1.5:\n",
    "        return \"TEKANAN RENDAH (REBUSAN TIDAK MATANG)\"\n",
    "    elif 1.5 <= tekanan_bar <= 3.0:\n",
    "        return \"TEKANAN OPTIMAL (STERILISASI NORMAL)\"\n",
    "    else:\n",
    "        return \"BAHAYA: OVERPRESSURE (BUKA KATUP DARURAT)\"\n",
    "\n",
    "# Pengujian Tantangan 1\n",
    "print(\"=== TANTANGAN 1: EVALUASI TEKANAN STERILIZER ===\")\n",
    "uji_tekanan = [-0.5, 1.2, 2.4, 3.5]\n",
    "for p in uji_tekanan:\n",
    "    print(f\"Tekanan {p:>4.1f} Bar -> Status: {evaluasi_tekanan_sterilizer(p)}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# === TANTANGAN 2: DETEKSI KEMATANGAN BERBASIS WARNA HSV ===\n",
    "def deteksi_kematangan_hsv(hue: float, sat: float) -> str:\n",
    "    \"\"\"\n",
    "    Mengevaluasi tingkat kematangan buah sawit dari sinyal kamera visi komputer HSV.\n",
    "    Menggunakan pola Guard Clauses linier.\n",
    "    \"\"\"\n",
    "    # Guard 1: Validasi rentang fisik nilai sensor\n",
    "    if not (0.0 <= hue <= 360.0 and 0.0 <= sat <= 100.0):\n",
    "        return \"ERROR: PARAMETER HSV DI LUAR JANGKAUAN\"\n",
    "\n",
    "    # Guard 2: Kategori Hijau / Mentah\n",
    "    if 60.0 <= hue <= 110.0 and sat >= 40.0:\n",
    "        return \"HIJAU / MENTAH (FRAKSI 0/1)\"\n",
    "\n",
    "    # Guard 3: Kategori Oranye / Matang Sempurna\n",
    "    if 25.0 <= hue <= 59.0 and sat >= 50.0:\n",
    "        return \"ORANYE / MATANG SEMPURNA (FRAKSI 2)\"\n",
    "\n",
    "    # Guard 4: Kategori Merah Tua / Lewat Matang\n",
    "    if (0.0 <= hue <= 24.0 or hue >= 340.0) and sat >= 40.0:\n",
    "        return \"MERAH TUA / LEWAT MATANG (FRAKSI 3)\"\n",
    "\n",
    "    # Fallback jika warna kusam/tidak memenuhi syarat\n",
    "    return \"ANOMALI WARNA / PERLU INSPEKSI ULANG\"\n",
    "\n",
    "# Pengujian Tantangan 2\n",
    "print(\"\\n=== TANTANGAN 2: DETEKSI WARNA HSV TBS ===\")\n",
    "sampel_hsv = [\n",
    "    (85.0, 65.0),\n",
    "    (38.0, 75.0),\n",
    "    (15.0, 60.0),\n",
    "    (350.0, 70.0),\n",
    "    (180.0, 20.0),\n",
    "]\n",
    "for h, s in sampel_hsv:\n",
    "    print(f\"Hue: {h:>5.1f}, Sat: {s:>4.1f}% -> Klasifikasi: {deteksi_kematangan_hsv(h, s)}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# === TANTANGAN 3: INDUSTRIAL EMERGENCY TRIAGE ENGINE ===\n",
    "class IndustrialEmergencyTriage:\n",
    "    \"\"\"\n",
    "    Engine triage darurat stasiun perebusan & turbin PKS multi-sensor.\n",
    "    Memanfaatkan Guard Clauses hierarkis fail-fast.\n",
    "    \"\"\"\n",
    "    def __init__(self) -> None:\n",
    "        self.log_insiden: List[str] = []\n",
    "\n",
    "    def evaluasi_kondisi(self, tekanan_bar: float, suhu_c: float, getaran_v_mms: float) -> str:\n",
    "        # Guard 1: KODE MERAH (Kegagalan Kritis - Shutdown Seketika)\n",
    "        if tekanan_bar > 3.2 or getaran_v_mms > 7.5:\n",
    "            pesan = f\"KODE MERAH: EMERGENCY SHUTDOWN! (P={tekanan_bar} Bar, V={getaran_v_mms} mm/s)\"\n",
    "            self.log_insiden.append(pesan)\n",
    "            return \"KODE MERAH\"\n",
    "\n",
    "        # Guard 2: KODE KUNING (Peringatan & Throttling)\n",
    "        if (tekanan_bar > 2.8) or (getaran_v_mms > 4.5) or (suhu_c > 98.0):\n",
    "            pesan = f\"KODE KUNING: THROTTLING OPERASI (P={tekanan_bar} Bar, T={suhu_c} C, V={getaran_v_mms} mm/s)\"\n",
    "            self.log_insiden.append(pesan)\n",
    "            return \"KODE KUNING\"\n",
    "\n",
    "        # Happy Path: Operasi Pabrik Aman\n",
    "        return \"KODE HIJAU\"\n",
    "\n",
    "# Simulasi Aliran Data Multi-Sensor Stasiun Turbin PKS\n",
    "triage = IndustrialEmergencyTriage()\n",
    "telemetri_pks = [\n",
    "    (2.1, 85.0, 2.1), # Normal\n",
    "    (2.3, 88.0, 2.5), # Normal\n",
    "    (2.9, 92.0, 3.2), # Kuning (Tekanan naik)\n",
    "    (2.5, 99.5, 3.8), # Kuning (Suhu panas)\n",
    "    (3.4, 91.0, 4.0), # Merah (Overpressure)\n",
    "    (2.2, 86.0, 8.2), # Merah (Getaran turbin kritis)\n",
    "]\n",
    "\n",
    "print(\"\\n=== TANTANGAN 3: INDUSTRIAL EMERGENCY TRIAGE ENGINE ===\")\n",
    "status_list = []\n",
    "for t, (p, s, v) in enumerate(telemetri_pks):\n",
    "    status = triage.evaluasi_kondisi(p, s, v)\n",
    "    status_list.append(status)\n",
    "    print(f\"Detik ke-{t:02d} | P={p} Bar, T={s} C, V={v} mm/s -> Status: [{status}]\")\n",
    "\n",
    "print(f\"\\nTotal Insiden Tercatat di Audit Log: {len(triage.log_insiden)} Kejadian.\")\n",
    "for log in triage.log_insiden:\n",
    "    print(f\"  [LOG] {log}\")"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

output_path = "notebooks/part-02/AI_Modul_2.6_Praktikum_Percabangan_If_Else.ipynb"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"[BERHASIL] File Jupyter Notebook tersimpan di: {output_path}")
