import json
import os
import sys

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<a href=\"https://colab.research.google.com/\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>\n",
    "\n",
    "# AI Modul 2.9: Praktikum Struktur Data Dasar\n",
    "### Taksonomi Koleksi Fundamental, Model Memori Hash Table versus Larik Kontigu, Analisis Kompleksitas Big-O, dan Pengorganisasian Mahadata Perkebunan\n",
    "\n",
    "---\n",
    "\n",
    "> **Diktat Terkait:** [AI_Modul_2.9_Struktur_Data_Dasar.md](../../docs/part-02/AI_Modul_2.9_Struktur_Data_Dasar.md)  \n",
    "> **Outputs:** Skrip implementasi dan manipulasi empat struktur data dasar (`list`, `tuple`, `dict`, `set`), tabel matriks benchmark empiris Big-O, serta pipeline agregasi data panen kelapa sawit skala industri perkebunan.  \n",
    "> **Outcomes:** Mahasiswa terampil memilih representasi data optimal berdasarkan karakteristik beban kerja, memahami model memori fisik CPython (larik kontigu vs tabel hash), serta mahir merekayasa fitur menggunakan ekspresi komprehensi deklaratif.  \n",
    "> **Impacts:** Mendorong efisiensi infrastruktur pengolahan mahadata perkebunan (*agri-logistics*), optimasi alokasi RAM pada perangkat komputasi tepi (*Edge AI IoT*), dan meletakkan fondasi kokoh menuju manipulasi matriks/tensor machine learning.\n",
    ">\n",
    "> **Tujuan Praktikum:**  \n",
    "> 1. Mengukur performa empiris waktu pencarian keanggotaan $\\mathcal{O}(1)$ vs $\\mathcal{O}(N)$ pada `list` dan `set` dengan skala data $N = 200.000$.  \n",
    "> 2. Mengaudit arsitektur memori internal CPython, jejak ukuran memori (*footprint*), dan batasan imutabilitas kunci hashable.  \n",
    "> 3. Membangun pipeline transformasi data ringkas berbasis *list, dict, set comprehension*, dan *generator expressions*.  \n",
    "> 4. Mengimplementasikan sistem agregasi mahadata panen kelapa sawit terpadu (`EngineAgregasiPanen`).  \n",
    "> 5. Menyelesaikan 3 tantangan mandiri: penghitung frekuensi varietas, analisis disparitas hama Jaccard, dan indeks kanopi spasial berbasis radius filter."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Persiapan Environment & Pemuatan Library\n",
    "Jalankan sel berikut untuk memuat modul pustaka standar dan pustaka visualisasi grafik numerik:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import math\n",
    "import sys\n",
    "import time\n",
    "import random\n",
    "from dataclasses import dataclass\n",
    "from typing import Any, Dict, List, Set, Tuple, Optional\n",
    "\n",
    "# Modul numerik dan visualisasi\n",
    "import numpy as np\n",
    "import matplotlib\n",
    "matplotlib.use('Agg')\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Konfigurasi gaya visualisasi grafik\n",
    "plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')\n",
    "plt.rcParams['figure.dpi'] = 120\n",
    "plt.rcParams['font.size'] = 10\n",
    "\n",
    "print(\"[OK] Seluruh pustaka dasar dan analitika berhasil diinisialisasi.\")\n",
    "print(f\"[INFO] Interpreter: Python {sys.version.split()[0]} pada platform {sys.platform}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Eksperimen Kompleksitas Asimptotik Big-O: Larik Kontigu vs Tabel Hash\n",
    "Kita menguji perbedaan mendasar antara pencarian linier $\\mathcal{O}(N)$ pada `list` dan pencarian konstan $\\mathcal{O}(1)$ pada `set`/`dict` menggunakan pengujian empiris dengan $N = 200.000$ elemen acak."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Pembangkitan dataset berskala besar untuk benchmarking\n",
    "N_ELEMEN = 200_000\n",
    "random.seed(42)\n",
    "\n",
    "print(f\"[INFO] Membangkitkan dataset {N_ELEMEN:,} data acak...\")\n",
    "data_acak = [random.randint(1, 10_000_000) for _ in range(N_ELEMEN)]\n",
    "himpunan_acak = set(data_acak)\n",
    "\n",
    "# Target pencarian: Elemen di awal, tengah, akhir, dan elemen yang dipastikan tidak ada (Worst Case)\n",
    "target_awal = data_acak[10]\n",
    "target_tengah = data_acak[N_ELEMEN // 2]\n",
    "target_akhir = data_acak[-10]\n",
    "target_tidak_ada = -999_999\n",
    "\n",
    "skenario_uji = [\n",
    "    (\"Awal Larik\", target_awal),\n",
    "    (\"Tengah Larik\", target_tengah),\n",
    "    (\"Akhir Larik\", target_akhir),\n",
    "    (\"Tidak Ditemukan (Worst Case)\", target_tidak_ada)\n",
    "]\n",
    "\n",
    "hasil_benchmark = []\n",
    "JUMLAH_REPETISI = 20\n",
    "\n",
    "print(f\"\\n{'Skenario Pencarian':<30} | {'Waktu List (ms)':<18} | {'Waktu Set (ms)':<18} | {'Faktor Percepatan'}\")\n",
    "print(\"-\" * 85)\n",
    "\n",
    "for nama, target in skenario_uji:\n",
    "    # Benchmark List (O(N))\n",
    "    t0 = time.perf_counter()\n",
    "    for _ in range(JUMLAH_REPETISI):\n",
    "        _ = target in data_acak\n",
    "    t1 = time.perf_counter()\n",
    "    waktu_list_ms = ((t1 - t0) / JUMLAH_REPETISI) * 1000.0\n",
    "\n",
    "    # Benchmark Set (O(1))\n",
    "    t0 = time.perf_counter()\n",
    "    for _ in range(JUMLAH_REPETISI):\n",
    "        _ = target in himpunan_acak\n",
    "    t1 = time.perf_counter()\n",
    "    waktu_set_ms = ((t1 - t0) / JUMLAH_REPETISI) * 1000.0\n",
    "\n",
    "    speedup = waktu_list_ms / max(waktu_set_ms, 1e-9)\n",
    "    hasil_benchmark.append((nama, waktu_list_ms, waktu_set_ms, speedup))\n",
    "    print(f\"{nama:<30} | {waktu_list_ms:<18.4f} | {waktu_set_ms:<18.6f} | {speedup:>12.1f}x\")\n",
    "\n",
    "# Visualisasi Komparasi Waktu Eksekusi\n",
    "kategori = [item[0] for item in hasil_benchmark]\n",
    "w_list = [item[1] for item in hasil_benchmark]\n",
    "w_set = [item[2] for item in hasil_benchmark]\n",
    "\n",
    "x = np.arange(len(kategori))\n",
    "lebar = 0.35\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(9, 4.5))\n",
    "bar1 = ax.bar(x - lebar/2, w_list, lebar, label='List O(N) [Larik Kontigu]', color='indianred', alpha=0.9)\n",
    "bar2 = ax.bar(x + lebar/2, w_set, lebar, label='Set O(1) [Tabel Hash]', color='forestgreen', alpha=0.9)\n",
    "\n",
    "ax.set_ylabel('Rerata Waktu Pencarian (milidetik - Skala Logaritmik)', fontweight='bold')\n",
    "ax.set_yscale('log')\n",
    "ax.set_title(f'Komparasi Empiris Kompleksitas Big-O: List vs Set (N = {N_ELEMEN:,} Elemen)', fontweight='bold', fontsize=11)\n",
    "ax.set_xticks(x)\n",
    "ax.set_xticklabels(kategori, fontweight='bold')\n",
    "ax.legend(frameon=True)\n",
    "plt.tight_layout()\n",
    "plt.savefig('docs/assets/benchmark_kompleksitas_list_vs_set.png', dpi=150)\n",
    "print(\"\\n[INFO] Grafik benchmark Big-O berhasil disimpan ke 'docs/assets/benchmark_kompleksitas_list_vs_set.png'.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Arsitektur Memori Fisik CPython & Batasan Kunci Hashable\n",
    "Memeriksa jejak alokasi memori fisik (`sys.getsizeof`), strategi alokasi berlebih (*over-allocation*), serta pembuktian syarat imutabilitas kunci hash table."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. Analisis Jejak Memori Fisik Berbagai Struktur Data\n",
    "elemen_contoh = list(range(100))\n",
    "list_obj = list(elemen_contoh)\n",
    "tuple_obj = tuple(elemen_contoh)\n",
    "set_obj = set(elemen_contoh)\n",
    "dict_obj = {k: k for k in elemen_contoh}\n",
    "\n",
    "print(\"=== JEJAK MEMORI FISIK (100 ELEMEN INTEGER) ===\")\n",
    "print(f\"Tuple (Imutabel, Larik Statis) : {sys.getsizeof(tuple_obj):>6} byte\")\n",
    "print(f\"List  (Mutabel, Larik Dinamis) : {sys.getsizeof(list_obj):>6} byte\")\n",
    "print(f\"Set   (Tabel Hash Terkompresi) : {sys.getsizeof(set_obj):>6} byte\")\n",
    "print(f\"Dict  (Tabel Hash Berpasangan) : {sys.getsizeof(dict_obj):>6} byte\")\n",
    "\n",
    "# 2. Demonstrasi Mekanisme Dynamic Over-Allocation pada List\n",
    "print(\"\\n=== STRATEGI OVER-ALLOCATION LIST CPYTHON ===\")\n",
    "larik_uji = []\n",
    "ukuran_sebelumnya = sys.getsizeof(larik_uji)\n",
    "print(f\"Ukuran Awal (0 Elemen): {ukuran_sebelumnya} byte\")\n",
    "for i in range(25):\n",
    "    larik_uji.append(i)\n",
    "    ukuran_sekarang = sys.getsizeof(larik_uji)\n",
    "    if ukuran_sekarang != ukuran_sebelumnya:\n",
    "        print(f\"Panjang: {len(larik_uji):<3} | Alokasi Memori Melompat: {ukuran_sekarang} byte (Kapasitas Diperluas)\")\n",
    "        ukuran_sebelumnya = ukuran_sekarang\n",
    "\n",
    "# 3. Eksperimen Syarat Kunci Hashable (Tuple vs List)\n",
    "print(\"\\n=== VALIDASI KUNCI HASH TABLE ===\")\n",
    "koordinat_tuple = (0.952, 101.442)  # Imutabel -> Memiliki nilai hash tetap\n",
    "print(f\"Hash dari Tuple {koordinat_tuple} : {hash(koordinat_tuple)}\")\n",
    "kamus_pohon = {koordinat_tuple: \"Pohon Sawit Palma-01\"}\n",
    "print(f\"Sukses Menyimpan Tuple Sebagai Kunci: {kamus_pohon[koordinat_tuple]}\")\n",
    "\n",
    "koordinat_list = [0.952, 101.442]   # Mutabel -> Dilarang sebagai kunci\n",
    "try:\n",
    "    kamus_ilegal = {koordinat_list: \"Pohon Sawit Ilegal\"}\n",
    "except TypeError as e:\n",
    "    print(f\"Tertangkap TypeError (Harapan Terpenuhi): {e}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Manipulasi Data Deklaratif Berbasis Komprehensi\n",
    "Menerapkan *List, Dict, Set Comprehension*, serta *Generator Expression* untuk memproses data sensorik dan logistik secara bersih, cepat, dan hemat memori."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Dataset mentah hasil telemetri kebun\n",
    "suhu_harian = [27.5, 32.1, 24.8, 33.5, 29.2, 34.0, 26.5]\n",
    "afdeling_raw = [\"AFD-1\", \"AFD-2\", \"afd-1\", \"Afd-3\", \"AFD-2\", \"AFD-1 \"]\n",
    "data_blok = {\n",
    "    \"BLOK-A1\": {\"luas_ha\": 25.0, \"tanam\": 2015},\n",
    "    \"BLOK-A2\": {\"luas_ha\": 30.5, \"tanam\": 2012},\n",
    "    \"BLOK-B1\": {\"luas_ha\": 18.0, \"tanam\": 2018},\n",
    "}\n",
    "\n",
    "# 1. List Comprehension: Filter suhu panas ekstrem (> 30°C)\n",
    "suhu_ekstrem = [s for s in suhu_harian if s > 30.0]\n",
    "\n",
    "# 2. Set Comprehension: Deduplikasi dan standardisasi kode afdeling\n",
    "afdeling_bersih = {a.strip().upper() for a in afdeling_raw}\n",
    "\n",
    "# 3. Dict Comprehension: Estimasi alokasi pupuk NPK (250 kg/ha) untuk tanaman tua (tanam <= 2015)\n",
    "alokasi_pupuk = {\n",
    "    blok: info[\"luas_ha\"] * 250.0\n",
    "    for blok, info in data_blok.items()\n",
    "    if info[\"tanam\"] <= 2015\n",
    "}\n",
    "\n",
    "# 4. Generator Expression vs List Comprehension: Perbandingan Ukuran Memori\n",
    "GEN_N = 1_000_000\n",
    "gen_exp = (x * 1.5 for x in range(GEN_N))\n",
    "list_exp = [x * 1.5 for x in range(10_000)] # Hanya 10.000 untuk perbandingan aman\n",
    "\n",
    "print(\"=== HASIL TRANSFORMASI KOMPREHENSI ===\")\n",
    "print(f\"1. Suhu Ekstrem (> 30°C)       : {suhu_ekstrem}\")\n",
    "print(f\"2. Himpunan Afdeling Unik     : {afdeling_bersih}\")\n",
    "print(f\"3. Alokasi Pupuk Tanaman Tua  : {alokasi_pupuk}\")\n",
    "print(f\"4. Ukuran Memori Generator (1 Juta Elemen) : {sys.getsizeof(gen_exp)} byte (Evaluasi Malas / Lazy)\")\n",
    "print(f\"   Ukuran Memori List (10 Ribu Elemen)    : {sys.getsizeof(list_exp):,} byte (Evaluasi Langsung)\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Implementasi Terintegrasi: Pipeline Agregasi Mahadata Panen Sawit\n",
    "Membangun kelas `EngineAgregasiPanen` yang memadukan List, Tuple, Set, dan Dictionary untuk memvalidasi transaksi panen, mengagregasi tonase, dan memfilter blok prioritas."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "@dataclass(frozen=True)\n",
    "class TiketTimbanganTBS:\n",
    "    \"\"\"Objek data transfer transaksi timbangan janjang buah sawit.\"\"\"\n",
    "    id_tiket: str\n",
    "    id_pemanen: str\n",
    "    kode_blok: str\n",
    "    berat_tbs_kg: float\n",
    "    jumlah_janjang: int\n",
    "\n",
    "\n",
    "class EngineAgregasiPanen:\n",
    "    \"\"\"\n",
    "    Engine pemrosesan data panen skala besar menggunakan sinergi\n",
    "    List, Tuple, Set, dan Dictionary teroptimasi O(1).\n",
    "    \"\"\"\n",
    "    def __init__(self) -> None:\n",
    "        # Set: Basis data pemanen resmi terdaftar untuk verifikasi O(1)\n",
    "        self.registrasi_pemanen_sah: Set[str] = {\n",
    "            \"PMR-01\", \"PMR-02\", \"PMR-03\", \"PMR-04\", \"PMR-05\"\n",
    "        }\n",
    "        # Dict: Data referensi luas areal blok kebun (Hektar)\n",
    "        self.luas_blok_hektar: Dict[str, float] = {\n",
    "            \"BLOK-A01\": 25.5,\n",
    "            \"BLOK-A02\": 30.0,\n",
    "            \"BLOK-B01\": 22.0,\n",
    "            \"BLOK-B02\": 28.5,\n",
    "        }\n",
    "\n",
    "    def proses_batch_panen(self, transaksi_panen: List[TiketTimbanganTBS]) -> Dict[str, Any]:\n",
    "        \"\"\"Mengagregasi aliran transaksi panen ke dalam struktur data analitika terpadu.\"\"\"\n",
    "        # 1. Pemanfaatan Set untuk Verifikasi dan Deduplikasi O(1)\n",
    "        id_pemanen_lapangan: Set[str] = {t.id_pemanen for t in transaksi_panen}\n",
    "        pemanen_tidak_terdaftar: Set[str] = id_pemanen_lapangan - self.registrasi_pemanen_sah\n",
    "\n",
    "        # 2. Agregasi Tabular per Blok Menggunakan Nested Dictionary\n",
    "        rekapitulasi_blok: Dict[str, Dict[str, Any]] = {}\n",
    "\n",
    "        for t in transaksi_panen:\n",
    "            # Lewati pemanen yang tidak terdaftar (Security Guard Clause)\n",
    "            if t.id_pemanen in pemanen_tidak_terdaftar:\n",
    "                continue\n",
    "\n",
    "            if t.kode_blok not in rekapitulasi_blok:\n",
    "                rekapitulasi_blok[t.kode_blok] = {\n",
    "                    \"total_berat_kg\": 0.0,\n",
    "                    \"total_janjang\": 0,\n",
    "                    \"kumpulan_pemanen\": set(),   # Set untuk melacak pekerja unik\n",
    "                    \"riwayat_bobot\": []          # List untuk analisis distribusi bobot\n",
    "                }\n",
    "\n",
    "            blok_data = rekapitulasi_blok[t.kode_blok]\n",
    "            blok_data[\"total_berat_kg\"] += t.berat_tbs_kg\n",
    "            blok_data[\"total_janjang\"] += t.jumlah_janjang\n",
    "            blok_data[\"kumpulan_pemanen\"].add(t.id_pemanen)\n",
    "            blok_data[\"riwayat_bobot\"].append(t.berat_tbs_kg)\n",
    "\n",
    "        # 3. Transformasi Fitur AI Menggunakan Dict Comprehension\n",
    "        bjr_per_blok: Dict[str, float] = {\n",
    "            blok: round(info[\"total_berat_kg\"] / max(1, info[\"total_janjang\"]), 2)\n",
    "            for blok, info in rekapitulasi_blok.items()\n",
    "        }\n",
    "\n",
    "        produktivitas_ton_ha: Dict[str, float] = {\n",
    "            blok: round((info[\"total_berat_kg\"] / 1000.0) / self.luas_blok_hektar.get(blok, 1.0), 3)\n",
    "            for blok, info in rekapitulasi_blok.items()\n",
    "        }\n",
    "\n",
    "        # 4. Filter Blok Prioritas Menggunakan List of Tuples\n",
    "        blok_kinerja_tinggi: List[Tuple[str, float]] = [\n",
    "            (blok, ton_ha) for blok, ton_ha in produktivitas_ton_ha.items()\n",
    "            if ton_ha >= 0.08  # Ambang batas prioritas angkut\n",
    "        ]\n",
    "\n",
    "        return {\n",
    "            \"total_transaksi\": len(transaksi_panen),\n",
    "            \"pemanen_aktif\": sorted(list(id_pemanen_lapangan - pemanen_tidak_terdaftar)),\n",
    "            \"pemanen_ilegal\": sorted(list(pemanen_tidak_terdaftar)),\n",
    "            \"rekapitulasi_blok\": rekapitulasi_blok,\n",
    "            \"metrik_bjr_kg\": bjr_per_blok,\n",
    "            \"produktivitas_ton_ha\": produktivitas_ton_ha,\n",
    "            \"blok_prioritas_angkut\": blok_kinerja_tinggi\n",
    "        }\n",
    "\n",
    "# Eksekusi simulasi data panen harian perkebunan\naliran_panen = [\n",
    "    TiketTimbanganTBS(\"T-001\", \"PMR-01\", \"BLOK-A01\", 1450.0, 85),\n",
    "    TiketTimbanganTBS(\"T-002\", \"PMR-02\", \"BLOK-A01\", 1820.0, 105),\n",
    "    TiketTimbanganTBS(\"T-003\", \"PMR-01\", \"BLOK-A02\", 2100.0, 110),\n",
    "    TiketTimbanganTBS(\"T-004\", \"PMR-03\", \"BLOK-B01\", 1650.0, 92),\n",
    "    TiketTimbanganTBS(\"T-005\", \"PMR-04\", \"BLOK-A02\", 1950.0, 98),\n",
    "    TiketTimbanganTBS(\"T-006\", \"PMR-05\", \"BLOK-B02\", 2400.0, 115),\n",
    "    TiketTimbanganTBS(\"T-007\", \"PMR-99\", \"BLOK-B01\", 850.0, 45),   # Tenaga kerja ilegal!\n",
    "    TiketTimbanganTBS(\"T-008\", \"PMR-02\", \"BLOK-A01\", 1200.0, 68),\n",
    "]\n",
    "\n",
    "engine = EngineAgregasiPanen()\n",
    "laporan = engine.proses_batch_panen(aliran_panen)\n",
    "\n",
    "print(\"=\" * 75)\n",
    "print(\"HASIL AGREGASI MAHADATA PANEN KELAPA SAWIT INSTIPER\")\n",
    "print(\"=\" * 75)\n",
    "print(f\"Total Transaksi Masuk       : {laporan['total_transaksi']} tiket\")\n",
    "print(f\"Pemanen Aktif Terverifikasi : {laporan['pemanen_aktif']}\")\n",
    "print(f\"Peringatan Pemanen Ilegal   : {laporan['pemanen_ilegal']}\")\n",
    "\n",
    "print(\"\\nRekapitulasi Produksi per Blok Kebun:\")\n",
    "for blok, data in laporan[\"rekapitulasi_blok\"].items():\n",
    "    ton = data['total_berat_kg'] / 1000.0\n",
    "    bjr = laporan['metrik_bjr_kg'][blok]\n",
    "    prod = laporan['produktivitas_ton_ha'][blok]\n",
    "    pemanen = sorted(list(data['kumpulan_pemanen']))\n",
    "    print(f\" * [{blok}] Produksi: {ton:.2f} Ton ({data['total_janjang']} jjg) | Rerata BJR: {bjr} kg/jjg | Prod: {prod:.3f} Ton/Ha | Tim: {pemanen}\")\n",
    "\n",
    "print(\"\\nBlok Prioritas Pengangkutan Truk:\")\n",
    "for blok, prod in laporan[\"blok_prioritas_angkut\"]:\n",
    "    print(f\" -> {blok:<10} : {prod:.3f} Ton/Ha [STATUS: PRIORITAS ANGKUT CEPAT]\")\n",
    "\n",
    "# Visualisasi Analisis Produksi Blok\n",
    "blok_labels = list(laporan[\"rekapitulasi_blok\"].keys())\n",
    "tonase_values = [laporan[\"rekapitulasi_blok\"][b][\"total_berat_kg\"] / 1000.0 for b in blok_labels]\n",
    "bjr_values = [laporan[\"metrik_bjr_kg\"][b] for b in blok_labels]\n",
    "\n",
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))\n",
    "ax1.bar(blok_labels, tonase_values, color='forestgreen', alpha=0.85, edgecolor='black')\n",
    "ax1.set_title('Total Tonase Panen per Blok (Ton)', fontweight='bold')\n",
    "ax1.set_ylabel('Ton', fontweight='bold')\n",
    "\n",
    "ax2.bar(blok_labels, bjr_values, color='darkorange', alpha=0.85, edgecolor='black')\n",
    "ax2.set_title('Berat Janjang Rata-rata (BJR) (kg/janjang)', fontweight='bold')\n",
    "ax2.set_ylabel('kg/janjang', fontweight='bold')\n",
    "ax2.axhline(20.0, color='red', linestyle='--', label='Ambang Janjang Matang Prima (20 kg)')\n",
    "ax2.legend(fontsize=8)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('docs/assets/analisis_produksi_panen_per_blok.png', dpi=150)\n",
    "print(\"\\n[INFO] Grafik produksi blok berhasil disimpan ke 'docs/assets/analisis_produksi_panen_per_blok.png'.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Solusi Lengkap Tantangan Pemrograman Berjenjang\n",
    "Berikut adalah implementasi komprehensif dari 3 tantangan mandiri yang diberikan pada diktat modul:"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Tantangan 1 (Tingkat Dasar): Penghitungan Frekuensi Varietas Kelapa Sawit\n",
    "Menghitung kemunculan setiap varietas kelapa sawit pada pembibitan menggunakan `dict.get()` berkecepatan $\\mathcal{O}(N)$."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def hitung_frekuensi_varietas(daftar_bibit: List[str]) -> Dict[str, int]:\n",
    "    \"\"\"\n",
    "    Menghitung jumlah kemunculan setiap varietas bibit sawit dalam list\n",
    "    menggunakan dictionary O(1) key access tanpa modul eksternal.\n",
    "    \"\"\"\n",
    "    frekuensi: Dict[str, int] = {}\n",
    "    for bibit in daftar_bibit:\n",
    "        kode_bersih = bibit.strip()\n",
    "        frekuensi[kode_bersih] = frekuensi.get(kode_bersih, 0) + 1\n",
    "    return frekuensi\n",
    "\n",
    "# Pengujian Tantangan 1\n",
    "sensus_bibit = [\n",
    "    \"DxP-Marihat\", \"DxP-Yangambi\", \"DxP-Marihat\", \"DxP-Lame\",\n",
    "    \"DxP-Yangambi\", \"DxP-Marihat\", \"DxP-Avros\", \"DxP-Yangambi\"\n",
    "]\n",
    "hasil_frekuensi = hitung_frekuensi_varietas(sensus_bibit)\n",
    "\n",
    "print(\"=== TANTANGAN 1: FREKUENSI VARIETAS BIBIT SAWIT ===\")\n",
    "for varietas, jumlah in hasil_frekuensi.items():\n",
    "    print(f\"- Varietas {varietas:<15}: {jumlah} bibit\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Tantangan 2 (Tingkat Menengah): Analisis Irisan & Disparitas Hama Berbasis Set (Jaccard Index)\n",
    "Mengidentifikasi hama bersama, hama eksklusif, serta koefisien similaritas Jaccard antara dua divisi kebun."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def analisis_sebaran_hama(hama_afd1: Set[str], hama_afd2: Set[str]) -> Dict[str, Any]:\n",
    "    \"\"\"\n",
    "    Menganalisis distribusi spesies hama di dua afdeling kebun\n",
    "    menggunakan operasi aljabar himpunan (Set) berkecepatan O(min(len(s), len(t))).\n",
    "    \"\"\"\n",
    "    irisan = hama_afd1 & hama_afd2        # Hama di kedua afdeling\n",
    "    eksklusif_afd1 = hama_afd1 - hama_afd2 # Hama hanya di afdeling 1\n",
    "    eksklusif_afd2 = hama_afd2 - hama_afd1 # Hama hanya di afdeling 2\n",
    "    gabungan = hama_afd1 | hama_afd2       # Total seluruh varietas hama unik\n",
    "    \n",
    "    # Koefisien Similaritas Jaccard: J(A, B) = |A n B| / |A u B|\n",
    "    jaccard_index = len(irisan) / max(1, len(gabungan))\n",
    "\n",
    "    return {\n",
    "        \"hama_bersama\": sorted(list(irisan)),\n",
    "        \"eksklusif_afd1\": sorted(list(eksklusif_afd1)),\n",
    "        \"eksklusif_afd2\": sorted(list(eksklusif_afd2)),\n",
    "        \"total_spesies_unik\": len(gabungan),\n",
    "        \"jaccard_similarity\": round(jaccard_index, 4)\n",
    "    }\n",
    "\n",
    "# Pengujian Tantangan 2\n",
    "hama_divisi_1 = {\"Ulat Api\", \"Ulat Kantung\", \"Kumbang Tanduk\", \"Tikus Pohon\"}\n",
    "hama_divisi_2 = {\"Kumbang Tanduk\", \"Tikus Pohon\", \"Rayap Tanah\", \"Babi Hutan\"}\n",
    "\n",
    "hasil_hama = analisis_sebaran_hama(hama_divisi_1, hama_divisi_2)\n",
    "\n",
    "print(\"=== TANTANGAN 2: ANALISIS DISTRIBUSI HAMA VIA SET ===\")\n",
    "print(f\"Hama Muncul Bersama      : {hasil_hama['hama_bersama']}\")\n",
    "print(f\"Hama Eksklusif Divisi 1  : {hasil_hama['eksklusif_afd1']}\")\n",
    "print(f\"Hama Eksklusif Divisi 2  : {hasil_hama['eksklusif_afd2']}\")\n",
    "print(f\"Total Keanekaragaman Hama: {hasil_hama['total_spesies_unik']} spesies\")\n",
    "print(f\"Indeks Similaritas Jaccard : {hasil_hama['jaccard_similarity']} ({hasil_hama['jaccard_similarity']*100:.1f}% kesamaan)\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Tantangan 3 (Tingkat Mahir): Indeks Kanopi Spasial Pohon Sawit Berbasis Radius Filter\n",
    "Mengorganisasi pohon sawit dalam dictionary koordinat tuple `(grid_x, grid_y): skor_ndvi`, dan mendeteksi pohon terinfeksi ($NDVI < 0.35$) di dalam radius pantauan."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class SpatialCanopyIndex:\n",
    "    \"\"\"\n",
    "    Struktur data indeks spasial pohon sawit berbasis dictionary of tuples\n",
    "    untuk kueri radius cepat pada sistem surveilans drone.\n",
    "    \"\"\"\n",
    "    def __init__(self) -> None:\n",
    "        # Mapping: (grid_x, grid_y) -> skor_ndvi (float)\n",
    "        self.pohon_spasial: Dict[Tuple[int, int], float] = {}\n",
    "\n",
    "    def tambah_pohon(self, x: int, y: int, ndvi: float) -> None:\n",
    "        self.pohon_spasial[(x, y)] = ndvi\n",
    "\n",
    "    def cari_pohon_radius(\n",
    "        self, pusat_x: int, pusat_y: int, radius: int, ambang_terinfeksi: float = 0.35\n",
    "    ) -> List[Tuple[Tuple[int, int], float]]:\n",
    "        \"\"\"\n",
    "        Mengembalikan pohon dalam radius Euclidean yang mengalami infeksi/stres kanopi (NDVI < ambang).\n",
    "        Menggunakan List Comprehension efisien.\n",
    "        \"\"\"\n",
    "        r_kuadrat = radius ** 2\n",
    "        return [\n",
    "            (pos, ndvi) for pos, ndvi in self.pohon_spasial.items()\n",
    "            if ((pos[0] - pusat_x)**2 + (pos[1] - pusat_y)**2 <= r_kuadrat) and (ndvi < ambang_terinfeksi)\n",
    "        ]\n",
    "\n",
    "# Pengujian Tantangan 3 & Visualisasi Peta Spasial Kebun\n",
    "indeks_spasial = SpatialCanopyIndex()\n",
    "\n",
    "# Simulasi grid blok kebun 15x15 pohon\n",
    "np.random.seed(101)\n",
    "for gx in range(15):\n",
    "    for gy in range(15):\n",
    "        # Sebagian besar pohon sehat (NDVI 0.60 - 0.85), beberapa terinfeksi Ganoderma (NDVI 0.20 - 0.34)\n",
    "        is_sakit = np.random.rand() < 0.15\n",
    "        skor = np.random.uniform(0.18, 0.34) if is_sakit else np.random.uniform(0.60, 0.85)\n",
    "        indeks_spasial.tambah_pohon(gx, gy, round(skor, 3))\n",
    "\n",
    "# Titik pantauan drone surveilans\n",
    "CENTER_X, CENTER_Y, RADIUS_UJI = 7, 7, 4\n",
    "terinfeksi_radius = indeks_spasial.cari_pohon_radius(CENTER_X, CENTER_Y, RADIUS_UJI, ambang_terinfeksi=0.35)\n",
    "\n",
    "print(\"=== TANTANGAN 3: DETEKSI KANOPI SPASIAL BERBASIS RADIUS ===\")\n",
    "print(f\"Titik Pusat Pantauan Drone : ({CENTER_X}, {CENTER_Y}) | Radius: {RADIUS_UJI} grid\")\n",
    "print(f\"Ditemukan {len(terinfeksi_radius)} pohon stres/terinfeksi dalam radius pantauan:\")\n",
    "for pos, ndvi in terinfeksi_radius:\n",
    "    jarak = math.sqrt((pos[0]-CENTER_X)**2 + (pos[1]-CENTER_Y)**2)\n",
    "    print(f\" -> Koordinat {pos} | NDVI: {ndvi:.3f} | Jarak dari Pusat: {jarak:.2f} grid\")\n",
    "\n",
    "# Visualisasi Peta Sebaran Spasial\n",
    "fig, ax = plt.subplots(figsize=(7, 7))\n",
    "\n",
    "xs = [p[0] for p in indeks_spasial.pohon_spasial.keys()]\n",
    "ys = [p[1] for p in indeks_spasial.pohon_spasial.keys()]\n",
    "ndvis = [indeks_spasial.pohon_spasial[p] for p in indeks_spasial.pohon_spasial.keys()]\n",
    "\n",
    "sc = ax.scatter(xs, ys, c=ndvis, cmap='RdYlGn', s=80, edgecolors='black', linewidth=0.5, label='Pohon Sawit')\n",
    "cbar = plt.colorbar(sc, ax=ax, fraction=0.046, pad=0.04)\n",
    "cbar.set_label('Indeks Kesehatan Kanopi (NDVI)', fontweight='bold')\n",
    "\n",
    "# Gambar lingkaran radius inspeksi\n",
    "lingkaran_inspeksi = plt.Circle((CENTER_X, CENTER_Y), RADIUS_UJI, color='blue', fill=False, linestyle='--', linewidth=2, label=f'Radius Surveilans Drone (R={RADIUS_UJI})')\n",
    "ax.add_patch(lingkaran_inspeksi)\n",
    "ax.plot(CENTER_X, CENTER_Y, marker='*', markersize=14, color='blue', label='Pusat Pemantauan')\n",
    "\n",
    "# Beri tanda lingkaran merah pada pohon sakit yang terdeteksi\n",
    "if terinfeksi_radius:\n",
    "    rx = [item[0][0] for item in terinfeksi_radius]\n",
    "    ry = [item[0][1] for item in terinfeksi_radius]\n",
    "    ax.scatter(rx, ry, s=180, facecolors='none', edgecolors='red', linewidth=2.5, label='Pohon Terinfeksi Terdeteksi')\n",
    "\n",
    "ax.set_title('Peta Indeks Spasial Kanopi Sawit & Filter Radius Drone', fontweight='bold', fontsize=11)\n",
    "ax.set_xlabel('Grid Koordinat X (Baris Pohon)', fontweight='bold')\n",
    "ax.set_ylabel('Grid Koordinat Y (Pasar Pikul)', fontweight='bold')\n",
    "ax.legend(loc='upper right', bbox_to_anchor=(1.35, 1.0), frameon=True)\n",
    "plt.tight_layout()\n",
    "plt.savefig('docs/assets/peta_spasial_kanopi_sawit.png', dpi=150, bbox_inches='tight')\n",
    "print(\"\\n[INFO] Visualisasi peta spasial kanopi berhasil disimpan ke 'docs/assets/peta_spasial_kanopi_sawit.png'.\")"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

output_path = "notebooks/part-02/AI_Modul_2.9_Praktikum_Struktur_Data_Dasar.ipynb"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"[BERHASIL] File Jupyter Notebook tersimpan di: {output_path}")
