import json
import os

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<a href=\"https://colab.research.google.com/\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>\n",
    "\n",
    "# AI Modul 2.2: Praktikum Flowchart dan Pseudocode\n",
    "### Perancangan Visual Diagram Alir ANSI/ISO 5807, Eksekusi Mesin Penelusur Pseudocode (Trace Table Engine), dan Logika Inferensi AI Agro-Industri\n",
    "\n",
    "---\n",
    "\n",
    "> **Diktat Terkait:** [AI_Modul_2.2_Flowchart_dan_Pseudocode.md](../../docs/part-02/AI_Modul_2.2_Flowchart_dan_Pseudocode.md)  \n",
    "> **Outputs:** Script pembuatan diagram alir modular berbasis visualisasi terprogram, mesin pelacak status variabel (*dry-run trace engine*), serta implementasi simulator sortasi cerdas berbasis ambang batas probabilitas AI.  \n",
    "> **Outcomes:** Mahasiswa terampil merepresentasikan alur komputasi visual dan tekstual, memvalidasi integritas logika sebelum coding, serta mencegah galat struktural seperti *infinite loop* dan *dead branch*.  \n",
    "> **Impacts:** Terciptanya standar dokumentasi rekayasa perangkat lunak AI yang presisi, mempercepat koordinasi tim riset multidisiplin di lingkungan agro-industri perkebunan kelapa sawit.\n",
    ">\n",
    "> **Tujuan Praktikum:**  \n",
    "> 1. Memvisualisasikan galeri 8 simbol standar ANSI/ISO 5807 secara terprogram menggunakan pustaka grafika visual.  \n",
    "> 2. Menggambar dan memanipulasi diagram alir pipeline inferensi AI berbasis *computer vision*.  \n",
    "> 3. Membangun mesin simulator *trace table* langkah-demi-langkah untuk membuktikan kebenaran logika (*logical correctness*) pseudocode.  \n",
    "> 4. Mengimplementasikan filter logika percabangan bertingkat untuk penyortiran mutu komoditas perkebunan secara deterministik."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Persiapan Environment & Pemuatan Library\n",
    "Jalankan sel berikut untuk memuat modul sistem, manipulasi data matriks, dan visualisasi grafik:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Mengimpor modul sistem interpreter\n",
    "import sys\n",
    "\n",
    "# Mengimpor modul pencatat waktu presisi\n",
    "import time\n",
    "\n",
    "# Mengimpor modul pengetikan terstruktur\n",
    "from typing import Dict, List, Tuple, Any\n",
    "\n",
    "# Mengimpor pustaka numerik dan visualisasi\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.patches as patches\n",
    "\n",
    "# Mengatur konfigurasi visualisasi grafik\n",
    "plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')\n",
    "plt.rcParams['figure.dpi'] = 120\n",
    "\n",
    "# Menampilkan informasi lingkungan eksekusi\n",
    "print(f\"Python Version : {sys.version.split()[0]}\")\n",
    "print(\"[OK] Seluruh modul visualisasi dan simulasi berhasil dimuat dengan sukses!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Galeri Visual 8 Simbol Standar Diagram Alir (ANSI/ISO 5807)\n",
    "Jalankan sel berikut untuk merender katalog 8 simbol standar ANSI/ISO 5807 secara terprogram lengkap dengan karakteristik geometris dan fungsinya dalam pipeline kecerdasan buatan."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def tampilkan_galeri_simbol_ansi():\n",
    "    \"\"\"Menampilkan galeri visual 8 simbol standar ANSI/ISO 5807 untuk AI.\"\"\"\n",
    "    fig, axes = plt.subplots(4, 2, figsize=(11, 9.5), dpi=120)\n",
    "    axes = axes.flatten()\n",
    "\n",
    "    simbol_list = [\n",
    "        ('1. Terminator (Oval)', 'round', '#EBF8FF', '#3182CE', 'START / STOP\\nTitik Awal & Akhir Sistem'),\n",
    "        ('2. Process (Persegi Panjang)', 'rect', '#FEFCBF', '#D69E2E', 'Operasi / Komputasi\\nX = W * X + B (Tensor Matriks)'),\n",
    "        ('3. Decision (Belah Ketupat)', 'diamond', '#FED7D7', '#E53E3E', 'Percabangan Logika\\nApakah P >= 0.85? (Ya/Tidak)'),\n",
    "        ('4. Input / Output (Jajaran Genjang)', 'parallelogram', '#C6F6D5', '#38A169', 'Baca Kamera CCTV /\\nKirim Sinyal Aktuator Pneumatik'),\n",
    "        ('5. Preparation (Segi Enam)', 'hexagon', '#E9D8FD', '#805AD5', 'Inisialisasi Parameter\\nEpoch = 1, Lr = 0.001, Idx = 0'),\n",
    "        ('6. Connector On-Page (Lingkaran)', 'circle', '#EDF2F7', '#4A5568', 'Penghubung [A]\\nJalur Loop Se-Halaman'),\n",
    "        ('7. Predefined Process (Subrutin)', 'subroutine', '#E2E8F0', '#2B6CB0', 'Subrutin Model Deep Learning\\nYOLOv8_Detect(frame)'),\n",
    "        ('8. Off-Page Connector (Segi Lima)', 'pentagon', '#FEEBC8', '#DD6B20', 'Penghubung Antar-Halaman\\nLanjut ke Halaman [B]')\n",
    "    ]\n",
    "\n",
    "    for idx, (title, stype, bg, ec, txt) in enumerate(simbol_list):\n",
    "        ax = axes[idx]\n",
    "        ax.set_xlim(0, 4)\n",
    "        ax.set_ylim(0, 2.2)\n",
    "        ax.axis('off')\n",
    "        ax.set_title(title, fontsize=9.5, fontweight='bold', color='#1A365D', pad=4)\n",
    "        cx, cy = 2.0, 1.05\n",
    "        w, h = 2.4, 0.9\n",
    "        if stype == 'round':\n",
    "            p = patches.FancyBboxPatch((cx - w/2, cy - h/2), w, h, boxstyle='round,pad=0.2', fc=bg, ec=ec, lw=2)\n",
    "            ax.add_patch(p)\n",
    "        elif stype == 'rect':\n",
    "            p = patches.Rectangle((cx - w/2, cy - h/2), w, h, fc=bg, ec=ec, lw=2)\n",
    "            ax.add_patch(p)\n",
    "        elif stype == 'diamond':\n",
    "            pts = [[cx, cy + h*0.65], [cx + w*0.55, cy], [cx, cy - h*0.65], [cx - w*0.55, cy]]\n",
    "            p = patches.Polygon(pts, closed=True, fc=bg, ec=ec, lw=2)\n",
    "            ax.add_patch(p)\n",
    "        elif stype == 'parallelogram':\n",
    "            pts = [[cx - w/2 - 0.3, cy - h/2], [cx + w/2 - 0.3, cy - h/2], [cx + w/2 + 0.3, cy + h/2], [cx - w/2 + 0.3, cy + h/2]]\n",
    "            p = patches.Polygon(pts, closed=True, fc=bg, ec=ec, lw=2)\n",
    "            ax.add_patch(p)\n",
    "        elif stype == 'hexagon':\n",
    "            ho = 0.3\n",
    "            pts = [[cx - w/2 - ho, cy], [cx - w/2, cy + h/2], [cx + w/2, cy + h/2], [cx + w/2 + ho, cy], [cx + w/2, cy - h/2], [cx - w/2, cy - h/2]]\n",
    "            p = patches.Polygon(pts, closed=True, fc=bg, ec=ec, lw=2)\n",
    "            ax.add_patch(p)\n",
    "        elif stype == 'circle':\n",
    "            p = patches.Circle((cx, cy), 0.45, fc=bg, ec=ec, lw=2)\n",
    "            ax.add_patch(p)\n",
    "        elif stype == 'subroutine':\n",
    "            p = patches.Rectangle((cx - w/2, cy - h/2), w, h, fc=bg, ec=ec, lw=2)\n",
    "            ax.add_patch(p)\n",
    "            ax.plot([cx - w/2 + 0.25, cx - w/2 + 0.25], [cy - h/2, cy + h/2], color=ec, lw=1.8)\n",
    "            ax.plot([cx + w/2 - 0.25, cx + w/2 - 0.25], [cy - h/2, cy + h/2], color=ec, lw=1.8)\n",
    "        elif stype == 'pentagon':\n",
    "            pts = [[cx - w/2, cy + h/2], [cx + w/2, cy + h/2], [cx + w/2, cy - h/4], [cx, cy - h*0.65], [cx - w/2, cy - h/4]]\n",
    "            p = patches.Polygon(pts, closed=True, fc=bg, ec=ec, lw=2)\n",
    "            ax.add_patch(p)\n",
    "        ax.text(cx, cy, txt, ha='center', va='center', fontsize=7.5, fontweight='bold', color='#2D3748')\n",
    "\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "\n",
    "# Memanggil fungsi galeri simbol\n",
    "tampilkan_galeri_simbol_ansi()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Visualisasi Arsitektur Pipeline Sortasi AI TBS Sawit\n",
    "Sel berikut memadukan simbol-simbol di atas menjadi satu kesatuan diagram alir yang memetakan tahapan inferensi visi komputer untuk penyortiran kelapa sawit di pabrik."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def gambar_flowchart_inspeksi_sawit():\n",
    "    \"\"\"Menghasilkan visualisasi diagram alir inspeksi mutu kelapa sawit.\"\"\"\n",
    "    fig, ax = plt.subplots(figsize=(9, 8), dpi=120)\n",
    "    ax.set_xlim(0, 10)\n",
    "    ax.set_ylim(0, 10)\n",
    "    ax.axis('off')\n",
    "\n",
    "    # Judul Diagram\n",
    "    ax.text(5, 9.6, 'DIAGRAM ALIR INFERENSI SORTASI TBS SAWIT (ANSI/ISO 5807)', \n",
    "            ha='center', va='center', fontsize=11, fontweight='bold', color='#1A365D')\n",
    "\n",
    "    # 1. Terminator Start\n",
    "    p_start = patches.FancyBboxPatch((3.5, 8.5), 3.0, 0.6, boxstyle='round,pad=0.15', \n",
    "                                      fc='#EBF8FF', ec='#3182CE', lw=2)\n",
    "    ax.add_patch(p_start)\n",
    "    ax.text(5, 8.8, 'MULAI (Start)', ha='center', va='center', fontsize=9, fontweight='bold', color='#2B6CB0')\n",
    "\n",
    "    # 2. Input Frame Citra\n",
    "    p_in = patches.Polygon([[3.6, 7.2], [6.6, 7.2], [6.2, 7.9], [3.2, 7.9]], \n",
    "                           closed=True, fc='#C6F6D5', ec='#38A169', lw=2)\n",
    "    ax.add_patch(p_in)\n",
    "    ax.text(4.9, 7.55, 'INPUT: Baca Citra Kamera', ha='center', va='center', fontsize=8.5, fontweight='bold', color='#22543D')\n",
    "\n",
    "    # 3. Proses Inferensi AI\n",
    "    p_proc = patches.Rectangle((3.2, 5.9), 3.6, 0.7, fc='#FEFCBF', ec='#D69E2E', lw=2)\n",
    "    ax.add_patch(p_proc)\n",
    "    ax.text(5, 6.25, 'PROSES: Inferensi Model AI\\nHitung Probabilitas P(x)', ha='center', va='center', \n",
    "            fontsize=8, fontweight='bold', color='#744210')\n",
    "\n",
    "    # 4. Decision Diamond\n",
    "    pts_dec = [[5, 5.2], [6.8, 4.5], [5, 3.8], [3.2, 4.5]]\n",
    "    p_dec = patches.Polygon(pts_dec, closed=True, fc='#FED7D7', ec='#E53E3E', lw=2)\n",
    "    ax.add_patch(p_dec)\n",
    "    ax.text(5, 4.5, 'Apakah\\nP >= 0.85?', ha='center', va='center', fontsize=8.5, fontweight='bold', color='#9B2C2C')\n",
    "\n",
    "    # 5. Output Cabang Ya (Grade A)\n",
    "    p_out_a = patches.Polygon([[6.9, 2.7], [9.3, 2.7], [8.9, 3.4], [6.5, 3.4]], \n",
    "                              closed=True, fc='#C6F6D5', ec='#38A169', lw=2)\n",
    "    ax.add_patch(p_out_a)\n",
    "    ax.text(7.9, 3.05, 'OUTPUT: GRADE A\\nKirim ke PKS', ha='center', va='center', fontsize=7.5, fontweight='bold', color='#22543D')\n",
    "\n",
    "    # 6. Output Cabang Tidak (Sortir Manual)\n",
    "    p_out_b = patches.Polygon([[0.7, 2.7], [3.1, 2.7], [2.7, 3.4], [0.3, 3.4]], \n",
    "                              closed=True, fc='#FED7D7', ec='#E53E3E', lw=2)\n",
    "    ax.add_patch(p_out_b)\n",
    "    ax.text(1.7, 3.05, 'OUTPUT: EVALUASI\\nSortir Manual', ha='center', va='center', fontsize=7.5, fontweight='bold', color='#9B2C2C')\n",
    "\n",
    "    # 7. Terminator Stop\n",
    "    p_stop = patches.FancyBboxPatch((3.7, 1.2), 2.6, 0.6, boxstyle='round,pad=0.15', \n",
    "                                     fc='#EBF8FF', ec='#3182CE', lw=2)\n",
    "    ax.add_patch(p_stop)\n",
    "    ax.text(5, 1.5, 'SELESAI (End)', ha='center', va='center', fontsize=9, fontweight='bold', color='#2B6CB0')\n",
    "\n",
    "    # Garis Panah Penghubung\n",
    "    arrow_props = dict(arrowstyle='->', lw=1.6, color='#2D3748')\n",
    "    ax.annotate('', xy=(5, 7.9), xytext=(5, 8.5), arrowprops=arrow_props)\n",
    "    ax.annotate('', xy=(5, 6.6), xytext=(5, 7.2), arrowprops=arrow_props)\n",
    "    ax.annotate('', xy=(5, 5.2), xytext=(5, 5.9), arrowprops=arrow_props)\n",
    "\n",
    "    # Panah Decision Ya (Kanan)\n",
    "    ax.annotate('', xy=(6.8, 4.5), xytext=(7.9, 4.5), arrowprops=dict(lw=1.6, color='#2D3748'))\n",
    "    ax.annotate('', xy=(7.9, 3.4), xytext=(7.9, 4.5), arrowprops=arrow_props)\n",
    "    ax.text(7.2, 4.65, 'Ya', fontsize=9, fontweight='bold', color='#276749')\n",
    "\n",
    "    # Panah Decision Tidak (Kiri)\n",
    "    ax.annotate('', xy=(3.2, 4.5), xytext=(1.7, 4.5), arrowprops=dict(lw=1.6, color='#2D3748'))\n",
    "    ax.annotate('', xy=(1.7, 3.4), xytext=(1.7, 4.5), arrowprops=arrow_props)\n",
    "    ax.text(2.3, 4.65, 'Tidak', fontsize=9, fontweight='bold', color='#9B2C2C')\n",
    "\n",
    "    # Panah Menuju Terminator Selesai\n",
    "    ax.annotate('', xy=(5, 1.8), xytext=(7.9, 1.8), arrowprops=dict(lw=1.6, color='#2D3748'))\n",
    "    ax.annotate('', xy=(7.9, 1.8), xytext=(7.9, 2.7), arrowprops=dict(lw=1.6, color='#2D3748'))\n",
    "    ax.annotate('', xy=(5, 1.8), xytext=(1.7, 1.8), arrowprops=dict(lw=1.6, color='#2D3748'))\n",
    "    ax.annotate('', xy=(1.7, 1.8), xytext=(1.7, 2.7), arrowprops=dict(lw=1.6, color='#2D3748'))\n",
    "    ax.annotate('', xy=(5, 1.5), xytext=(5, 1.8), arrowprops=arrow_props)\n",
    "\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "\n",
    "# Memanggil fungsi visualisasi diagram alir\n",
    "gambar_flowchart_inspeksi_sawit()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Mesin Simulasi Penelusuran Logika (Algorithm Trace Engine)\n",
    "Sebelum menjalankan kode di lingkungan perangkat keras pabrik, insinyur melakukan *dry run*. Sel berikut mengimplementasikan mesin penelusur jejak (*trace table engine*) yang mencatat setiap evaluasi logika, mutasi variabel, dan instruksi aktuator."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class TraceTableEngine:\n",
    "    \"\"\"Mesin simulator pencatat jejak eksekusi logika pseudocode langkah-demi-langkah.\"\"\"\n",
    "    def __init__(self):\n",
    "        # Inisialisasi daftar rekaman jejak audit\n",
    "        self.logs: List[Dict[str, Any]] = []\n",
    "        self.step_counter: int = 1\n",
    "\n",
    "    def record_step(self, entity_id: str, line_desc: str, var_state: Dict[str, Any], \n",
    "                    condition_eval: str, action: str) -> None:\n",
    "        \"\"\"Merekam satu langkah eksekusi ke dalam tabel jejak.\"\"\"\n",
    "        self.logs.append({\n",
    "            \"Langkah\": self.step_counter,\n",
    "            \"Entitas\": entity_id,\n",
    "            \"Deskripsi Instruksi\": line_desc,\n",
    "            \"Status Variabel\": str(var_state),\n",
    "            \"Evaluasi Logika\": condition_eval,\n",
    "            \"Aksi / Output\": action\n",
    "        })\n",
    "        self.step_counter += 1\n",
    "\n",
    "    def cetak_tabel_jejak(self) -> None:\n",
    "        \"\"\"Menampilkan tabel audit jejak eksekusi dengan format terstruktur.\"\"\"\n",
    "        print(\"=\" * 100)\n",
    "        print(\"TABEL PENELUSURAN STATUS LOGIKA (TRACE TABLE AUDIT LOG)\")\n",
    "        print(\"=\" * 100)\n",
    "        header = f\"{'Langkah':<8} | {'Entitas':<10} | {'Evaluasi Logika':<24} | {'Status Variabel':<26} | {'Aksi / Output'}\"\n",
    "        print(header)\n",
    "        print(\"-\" * 100)\n",
    "        for row in self.logs:\n",
    "            step_str = f\"Step-{row['Langkah']}\"\n",
    "            print(f\"{step_str:<8} | {row['Entitas']:<10} | {row['Evaluasi Logika']:<24} | {row['Status Variabel']:<26} | {row['Aksi / Output']}\")\n",
    "        print(\"=\" * 100)\n",
    "        print(f\"[INFO] Total {len(self.logs)} langkah instruksi telah diaudit secara deterministik.\\n\")\n",
    "\n",
    "# Menguji mesin simulator jejak logika\n",
    "engine = TraceTableEngine()\n",
    "print(\"[OK] TraceTableEngine berhasil diinisialisasi!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Studi Kasus Agro-Industri: Pipeline Sortasi Multi-Ambang Batas\n",
    "Selanjutnya kita menjalankan simulasi pemilahan sekelompok Tandan Buah Segar (TBS) yang melintas di konveyor pabrik kelapa sawit menggunakan aturan percabangan terstruktur."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Menyiapkan data sampel uji TBS dengan variasi fitur visual dan skor AI\n",
    "dataset_tbs_uji = [\n",
    "    {\"id\": \"TBS-001\", \"warna\": \"Oranye Tua\", \"skor_p\": 0.94},\n",
    "    {\"id\": \"TBS-002\", \"warna\": \"Kuning Jingga\", \"skor_p\": 0.88},\n",
    "    {\"id\": \"TBS-003\", \"warna\": \"Kuning Kehijauan\", \"skor_p\": 0.67},\n",
    "    {\"id\": \"TBS-004\", \"warna\": \"Hijau Belum Matang\", \"skor_p\": 0.54},\n",
    "    {\"id\": \"TBS-005\", \"warna\": \"Hitam Pekat\", \"skor_p\": 0.18},\n",
    "    {\"id\": \"TBS-006\", \"warna\": \"Busuk Berjamur\", \"skor_p\": 0.05}\n",
    "]\n",
    "\n",
    "# Ambang batas keputusan (Decision Thresholds)\n",
    "THETA_HIGH = 0.85  # Syarat minimal Grade A (Matang)\n",
    "THETA_LOW  = 0.50  # Syarat minimal Grade B (Mengkal)\n",
    "\n",
    "# Menginisialisasi engine pencatat jejak baru\n",
    "tracer = TraceTableEngine()\n",
    "\n",
    "# Menjalankan simulasi penelusuran perulangan dan percabangan\n",
    "for tbs in dataset_tbs_uji:\n",
    "    t_id = tbs[\"id\"]\n",
    "    p_val = tbs[\"skor_p\"]\n",
    "    \n",
    "    # Evaluasi Cabang 1: Apakah P >= THETA_HIGH?\n",
    "    if p_val >= THETA_HIGH:\n",
    "        eval_str = f\"P({p_val}) >= 0.85 : TRUE\"\n",
    "        status_mutu = \"GRADE_A_MATANG\"\n",
    "        aktuasi_pks = \"Buka Katup Pneumatik 1 (Silo PKS)\"\n",
    "        tracer.record_step(t_id, \"IF P >= 0.85\", {\"P\": p_val, \"Mutu\": status_mutu}, eval_str, aktuasi_pks)\n",
    "    \n",
    "    # Evaluasi Cabang 2: Apakah P >= THETA_LOW?\n",
    "    elif p_val >= THETA_LOW:\n",
    "        eval_str = f\"P({p_val}) >= 0.50 : TRUE\"\n",
    "        status_mutu = \"GRADE_B_MENGKAL\"\n",
    "        aktuasi_pks = \"Buka Katup Pneumatik 2 (Pemeraman)\"\n",
    "        tracer.record_step(t_id, \"ELSE-IF P >= 0.50\", {\"P\": p_val, \"Mutu\": status_mutu}, eval_str, aktuasi_pks)\n",
    "    \n",
    "    # Evaluasi Cabang 3: Kondisi Gagal (Reject)\n",
    "    else:\n",
    "        eval_str = f\"P({p_val}) < 0.50  : TRUE\"\n",
    "        status_mutu = \"GRADE_C_MENTAH\"\n",
    "        aktuasi_pks = \"Pendorong Reject Aktif (Kompos)\"\n",
    "        tracer.record_step(t_id, \"ELSE (Fallback)\", {\"P\": p_val, \"Mutu\": status_mutu}, eval_str, aktuasi_pks)\n",
    "\n",
    "# Menampilkan hasil tabel jejak eksekusi lengkap\n",
    "tracer.cetak_tabel_jejak()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Tantangan Pemrograman Interaktif (Scaffolded Practice)\n",
    "\n",
    "### Tantangan: Sistem Pengendali Otomasi Irigasi Berbasis Hysteresis (Soil Moisture)\n",
    "Rancanglah sebuah fungsi logika Python yang mengimplementasikan sistem kontrol *hysteresis* untuk mencegah pompa air menyala-mati secara terlalu sering (*chattering*).\n",
    "\n",
    "**Spesifikasi Aturan:**\n",
    "- Masukan: `kelembaban_tanah` (persen float $0 - 100$), `status_pompa_saat_ini` (boolean: `True` untuk HIDUP, `False` untuk MATI).\n",
    "- Jika `kelembaban_tanah < 35.0`: Pompa wajib **HIDUP (`True`)**.\n",
    "- Jika `kelembaban_tanah > 65.0`: Pompa wajib **MATI (`False`)**.\n",
    "- Jika `35.0 <= kelembaban_tanah <= 65.0`: Status pompa **TETAP SAMA** seperti status sebelumnya (*hysteresis zone*)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def kendali_irigasi_hysteresis(kelembaban: float, status_pompa: bool) -> Tuple[bool, str]:\n",
    "    \"\"\"\n",
    "    Mengatur status pompa irigasi berdasarkan pembacaan kelembaban tanah dan status pompa eksisting.\n",
    "    \n",
    "    Returns:\n",
    "        Tuple[bool, str]: Status pompa baru (True/False) dan keterangan aksi sistem.\n",
    "    \"\"\"\n",
    "    # Validasi batas fisik sensor kelembaban\n",
    "    if kelembaban < 0.0 or kelembaban > 100.0:\n",
    "        raise ValueError(\"Nilai kelembaban tanah berada di luar batas sensor fisik (0-100%)\")\n",
    "    \n",
    "    # Logika Kontrol Hysteresis\n",
    "    if kelembaban < 35.0:\n",
    "        status_baru = True\n",
    "        keterangan = \"Tanah Kritis Kering: Pompa AKTIF\"\n",
    "    elif kelembaban > 65.0:\n",
    "        status_baru = False\n",
    "        keterangan = \"Tanah Sangat Lembab: Pompa NONAKTIF\"\n",
    "    else:\n",
    "        # Zona Hysteresis: Pertahankan status pompa sebelumnya\n",
    "        status_baru = status_pompa\n",
    "        keterangan = f\"Zona Aman ({kelembaban:.1f}%): Pertahankan status pompa ({'AKTIF' if status_pompa else 'NONAKTIF'})\"\n",
    "        \n",
    "    return status_baru, keterangan\n",
    "\n",
    "\n",
    "# Pengujian Suite Verifikasi Otomatis (Unit Test Logic)\n",
    "test_cases = [\n",
    "    (25.0, False, True),   # Tanah kering mendadak -> pompa harus nyala\n",
    "    (50.0, True, True),    # Masuk zona tengah saat pompa menyala -> tetap menyala\n",
    "    (75.0, True, False),   # Tanah jenuh air -> pompa harus mati\n",
    "    (55.0, False, False),  # Berada di zona tengah saat pompa mati -> tetap mati\n",
    "]\n",
    "\n",
    "print(\"=\" * 75)\n",
    "print(\"HASIL PENGUJIAN UNIT LOGIKA IRIGASI HYSTERESIS\")\n",
    "print(\"=\" * 75)\n",
    "semua_lulus = True\n",
    "for idx, (rh, pompa_awal, expected) in enumerate(test_cases, 1):\n",
    "    pompa_akhir, pesan = kendali_irigasi_hysteresis(rh, pompa_awal)\n",
    "    lulus = (pompa_akhir == expected)\n",
    "    status_uji = \"LULUS\" if lulus else \"GAGAL\"\n",
    "    print(f\"Uji #{idx} | RH: {rh:4.1f}% | Pompa Awal: {str(pompa_awal):<5} | Status Baru: {str(pompa_akhir):<5} | [{status_uji}] -> {pesan}\")\n",
    "    if not lulus:\n",
    "        semua_lulus = False\n",
    "\n",
    "print(\"=\" * 75)\n",
    "if semua_lulus:\n",
    "    print(\"[SUCCESS] 100% Kasus Uji Logika Lulus Sempurna!\")\n",
    "else:\n",
    "    print(\"[ALERT] Ditemukan kegagalan pada uji logika kontrol.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Rangkuman & Refleksi Praktikum\n",
    "\n",
    "Dari praktikum ini, kita telah membuktikan secara empiris bahwa:\n",
    "1. **Diagram Alir (Flowchart)** bukan sekadar gambar ilustrasi, melainkan spesifikasi formal yang dapat diverifikasi alur eksekusinya dan dirender secara terprogram.\n",
    "2. **Tabel Jejak (Trace Table)** memberikan transparansi mutlak terhadap status variabel di setiap siklus CPU, mengeliminasi dugaan-dugaan yang menjadi sumber utama timbulnya *bug* logika.\n",
    "3. Logika kontrol agro-industri membutuhkan penanganan komprehensif, termasuk batas aman (*defensive validation*) dan mekanisme stabilisasi seperti *hysteresis* agar sistem fisik tidak rusak akibat getaran frekuensi switching berlebih.\n",
    "\n",
    "Lanjutkan eksplorasi ke modul berikutnya: **AI Modul 2.3: Struktur Logika Pemrograman** untuk mendalami aljabar Boolean dan tabel kebenaran predikat majemuk!"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

output_path = r"e:\Project Buku\notebooks\part-02\AI_Modul_2.2_Praktikum_Flowchart_dan_Pseudocode.ipynb"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"Notebook successfully written to {output_path}")
