import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<a href=\"https://colab.research.google.com/\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>\n",
    "\n",
    "# AI Modul 1.3: Praktikum Perbedaan AI, Machine Learning, dan Deep Learning\n",
    "### Studi Komparasi Empiris Tiga Paradigma: Rule-Based AI vs Machine Learning Statistik vs Deep Learning Representasional\n",
    "\n",
    "---\n",
    "\n",
    "> **Diktat Terkait:** [AI_Modul_1.3_Perbedaan_AI_ML_dan_Deep_Learning.md](../../docs/part-01/AI_Modul_1.3_Perbedaan_AI_ML_dan_Deep_Learning.md)  \n",
    "> **Outputs:** Kode program implementasi 3 paradigma komputasi mandiri dengan komentar per baris, visualisasi bidang batas keputusan (*decision boundary*), dan grafik empiris kurva penskalaan data (*Data Scaling Curve*).  \n",
    "> **Outcomes:** Kemampuan analitis menentukan arsitektur komputasi yang paling proporsional untuk memecahkan masalah riil tanpa terjebak *overkill* atau inefisiensi arsitektur.  \n",
    "> **Impacts:** Penghematan anggaran daya komputasi dan kesiapan merancang pipeline data saintifik berstandar industri.  \n",
    ">\n",
    "> **Tujuan Pembelajaran:**  \n",
    "> 1. Membangun model sistem berbasis aturan (*Rule-Based*), model ML statistik (*Logistic Regression*), dan model jaringan syaraf tiruan (*Deep Neural Network*) dari nol (*from scratch*).  \n",
    "> 2. Mengukur dampak volume data latih ($N$) terhadap akurasi akhir masing-masing paradigma untuk membuktikan fenomena *saturation plateau*.  \n",
    "> 3. Memvisualisasikan perbedaan fleksibilitas batas keputusan linear vs non-linear secara grafis."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Persiapan Environment & Import Library\n",
    "Jalankan sel di bawah ini untuk memuat pustaka komputasi numerik dan perender grafik:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Mengimpor modul sys untuk pengecekan versi Python aktif\n",
    "import sys\n",
    "\n",
    "# Mengimpor modul numpy untuk komputasi matriks dan aljabar linier\n",
    "import numpy as np\n",
    "\n",
    "# Mengimpor modul matplotlib.pyplot untuk merender visualisasi grafik data\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Mengimpor Tuple dan List dari typing untuk dokumentasi tipe data\n",
    "from typing import Tuple, List\n",
    "\n",
    "# Menampilkan versi interpreter Python\n",
    "print(f\"Python Version : {sys.version.split()[0]}\")\n",
    "\n",
    "# Mengonfirmasi bahwa environment telah siap\n",
    "print(\"Environment siap digunakan untuk pengujian komparasi 3 paradigma!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Pembahasan Penggunaan Kode 1:\n",
    "- Kita menggunakan `numpy` secara murni untuk membangun ketiga arsitektur agar alur data dari forward pass, perhitungan error, hingga perambatan mundur (*backpropagation*) dapat diinspeksi secara transparan tanpa tertutup abstraksi pustaka tingkat tinggi."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Pembangkitan Dataset Sintetis Pertanian (Deteksi Daun Terinfeksi)\n",
    "Kita memodelkan 500 sampel inspeksi daun kelapa sawit dengan 2 fitur:\n",
    "- Fitur 1: Rasio kekuningan daun ($x_1 \\in [0.1, 0.9]$)\n",
    "- Fitur 2: Diameter bercak nekrotik ($x_2 \\in [0.5, 8.0]$ mm)\n",
    "Pola alami di lapangan memiliki relasi non-linier lengkung: daun sakit jika $(3.0 \\cdot x_1^2 + 0.15 \\cdot x_2^{1.5}) > 1.8$."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Mengunci nilai seed random numpy agar dataset identik dan eksperimen reproducible\n",
    "np.random.seed(42)\n",
    "\n",
    "# Menentukan jumlah total dataset sebanyak 500 sampel daun\n",
    "N_total = 500\n",
    "\n",
    "# Membangkitkan fitur rasio warna kuning daun (rentang 0.1 sampai 0.9)\n",
    "X1_yellow = np.random.uniform(0.1, 0.9, N_total)\n",
    "\n",
    "# Membangkitkan fitur ukuran diameter bercak daun dalam milimeter (rentang 0.5 sampai 8.0 mm)\n",
    "X2_spot = np.random.uniform(0.5, 8.0, N_total)\n",
    "\n",
    "# Menggabungkan kedua fitur menjadi matriks data 2-dimensi (500 x 2)\n",
    "X_data = np.column_stack([X1_yellow, X2_spot])\n",
    "\n",
    "# Menghitung label kondisi objektif menggunakan formula non-linier alamiah dengan sedikit noise stokastik\n",
    "noise = np.random.normal(0, 0.15, N_total)\n",
    "latent_formula = (3.0 * (X1_yellow ** 2)) + (0.15 * (X2_spot ** 1.5)) + noise\n",
    "y_labels = (latent_formula > 1.8).astype(int)\n",
    "\n",
    "print(f\"Total Sampel Data Berhasil Dibuat: {X_data.shape[0]} sampel\")\n",
    "print(f\"  Jumlah Daun Sehat (Kelas 0)     : {np.sum(y_labels == 0)}\")\n",
    "print(f\"  Jumlah Daun Sakit (Kelas 1)     : {np.sum(y_labels == 1)}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Implementasi Tiga Paradigma Model Komputasi\n",
    "Berikut adalah implementasi dari ketiga arsitektur:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ======================================================================\n",
    "# 1. MODEL PARADIGMA ATURAN (EXPERT RULE-BASED AI)\n",
    "# ======================================================================\n",
    "class RuleBasedInspector:\n",
    "    \"\"\"Model AI simbolik dengan batasan ambang batas manual dari pakar agronomi.\"\"\"\n",
    "    def __init__(self, yellow_th: float = 0.55, spot_th: float = 4.0):\n",
    "        self.yellow_th: float = yellow_th\n",
    "        self.spot_th: float = spot_th\n",
    "\n",
    "    def predict(self, X: np.ndarray) -> np.ndarray:\n",
    "        # Memeriksa kondisi apakah kedua parameter melebihi ambang batas pakar secara kaku\n",
    "        is_sick = (X[:, 0] > self.yellow_th) & (X[:, 1] > self.spot_th)\n",
    "        return is_sick.astype(int)\n",
    "\n",
    "\n",
    "# ======================================================================\n",
    "# 2. MODEL MACHINE LEARNING KLASIK (LOGISTIC REGRESSION)\n",
    "# ======================================================================\n",
    "class ClassicalLogisticRegression:\n",
    "    \"\"\"Model ML statistik linier dengan fungsi aktivasi Sigmoid dan optimasi Gradien.\"\"\"\n",
    "    def __init__(self, lr: float = 0.1, epochs: int = 300):\n",
    "        self.lr: float = lr\n",
    "        self.epochs: int = epochs\n",
    "        self.weights: np.ndarray = None\n",
    "        self.bias: float = 0.0\n",
    "\n",
    "    def _sigmoid(self, z: np.ndarray) -> np.ndarray:\n",
    "        # Menghitung fungsi sigmoid dengan proteksi pemotongan batas (clip)\n",
    "        clipped_z = np.clip(z, -500, 500)\n",
    "        return 1.0 / (1.0 + np.exp(-clipped_z))\n",
    "\n",
    "    def train(self, X: np.ndarray, y: np.ndarray) -> None:\n",
    "        n_samples, n_features = X.shape\n",
    "        self.weights = np.zeros(n_features)\n",
    "        self.bias = 0.0\n",
    "\n",
    "        for _ in range(self.epochs):\n",
    "            linear_z = np.dot(X, self.weights) + self.bias\n",
    "            y_prob = self._sigmoid(linear_z)\n",
    "            # Menghitung turunan gradien kerugian log-loss\n",
    "            dw = (1 / n_samples) * np.dot(X.T, (y_prob - y))\n",
    "            db = (1 / n_samples) * np.sum(y_prob - y)\n",
    "            # Memperbarui bobot berlawanan arah dengan gradien\n",
    "            self.weights -= self.lr * dw\n",
    "            self.bias -= self.lr * db\n",
    "\n",
    "    def predict(self, X: np.ndarray) -> np.ndarray:\n",
    "        linear_z = np.dot(X, self.weights) + self.bias\n",
    "        return (self._sigmoid(linear_z) >= 0.5).astype(int)\n",
    "\n",
    "\n",
    "# ======================================================================\n",
    "# 3. MODEL DEEP LEARNING (MINI MULTI-LAYER NEURAL NETWORK DENGAN RELU)\n",
    "# ======================================================================\n",
    "class MiniDeepNeuralNetwork:\n",
    "    \"\"\"Model jaringan syaraf dengan lapisan tersembunyi non-linier ReLU dan Backprop.\"\"\"\n",
    "    def __init__(self, input_dim: int = 2, hidden_dim: int = 8, lr: float = 0.1, epochs: int = 500):\n",
    "        self.lr: float = lr\n",
    "        self.epochs: int = epochs\n",
    "        # Inisialisasi bobot He-Normal\n",
    "        np.random.seed(42)\n",
    "        self.W1: np.ndarray = np.random.randn(input_dim, hidden_dim) * np.sqrt(2.0 / input_dim)\n",
    "        self.b1: np.ndarray = np.zeros((1, hidden_dim))\n",
    "        self.W2: np.ndarray = np.random.randn(hidden_dim, 1) * np.sqrt(2.0 / hidden_dim)\n",
    "        self.b2: np.ndarray = np.zeros((1, 1))\n",
    "\n",
    "    def _relu(self, z: np.ndarray) -> np.ndarray:\n",
    "        return np.maximum(0, z)\n",
    "\n",
    "    def _relu_deriv(self, z: np.ndarray) -> np.ndarray:\n",
    "        return (z > 0).astype(float)\n",
    "\n",
    "    def _sigmoid(self, z: np.ndarray) -> np.ndarray:\n",
    "        clipped_z = np.clip(z, -500, 500)\n",
    "        return 1.0 / (1.0 + np.exp(-clipped_z))\n",
    "\n",
    "    def train(self, X: np.ndarray, y: np.ndarray) -> None:\n",
    "        y_col = y.reshape(-1, 1)\n",
    "        n_samples = X.shape[0]\n",
    "\n",
    "        for _ in range(self.epochs):\n",
    "            # Forward Pass\n",
    "            Z1 = np.dot(X, self.W1) + self.b1\n",
    "            A1 = self._relu(Z1)\n",
    "            Z2 = np.dot(A1, self.W2) + self.b2\n",
    "            A2 = self._sigmoid(Z2)\n",
    "\n",
    "            # Backward Pass (Perambatan Balik Error)\n",
    "            dZ2 = A2 - y_col\n",
    "            dW2 = (1 / n_samples) * np.dot(A1.T, dZ2)\n",
    "            db2 = (1 / n_samples) * np.sum(dZ2, axis=0, keepdims=True)\n",
    "\n",
    "            dZ1 = np.dot(dZ2, self.W2.T) * self._relu_deriv(Z1)\n",
    "            dW1 = (1 / n_samples) * np.dot(X.T, dZ1)\n",
    "            db1 = (1 / n_samples) * np.sum(dZ1, axis=0, keepdims=True)\n",
    "\n",
    "            # Update Parameter\n",
    "            self.W2 -= self.lr * dW2\n",
    "            self.b2 -= self.lr * db2\n",
    "            self.W1 -= self.lr * dW1\n",
    "            self.b1 -= self.lr * db1\n",
    "\n",
    "    def predict(self, X: np.ndarray) -> np.ndarray:\n",
    "        Z1 = np.dot(X, self.W1) + self.b1\n",
    "        A1 = self._relu(Z1)\n",
    "        Z2 = np.dot(A1, self.W2) + self.b2\n",
    "        A2 = self._sigmoid(Z2)\n",
    "        return (A2 >= 0.5).astype(int).flatten()\n",
    "\n",
    "print(\"Ketiga kelas model berhasil didefinisikan!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Eksperimen Skalabilitas Data: Menguji Fenomena Saturation Plateau\n",
    "Kita menguji performa ketiga model pada berbagai ukuran data latih ($N = [20, 50, 100, 200, 400]$ sampel) dan mengevaluasi akurasinya pada 100 data uji terpisah:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Membagi data menjadi 400 sampel training dan 100 sampel testing independen\n",
    "X_train_full = X_data[:400]\n",
    "y_train_full = y_labels[:400]\n",
    "X_test = X_data[400:]\n",
    "y_test = y_labels[400:]\n",
    "\n",
    "# Variasi ukuran subset data latih yang akan diuji\n",
    "sample_sizes = [20, 50, 100, 200, 400]\n",
    "\n",
    "history_rule = []\n",
    "history_ml   = []\n",
    "history_dl   = []\n",
    "\n",
    "for n in sample_sizes:\n",
    "    X_sub = X_train_full[:n]\n",
    "    y_sub = y_train_full[:n]\n",
    "    \n",
    "    # 1. Rule-Based (Tidak membutuhkan pelatihan)\n",
    "    m_rule = RuleBasedInspector(yellow_th=0.55, spot_th=4.0)\n",
    "    pred_r = m_rule.predict(X_test)\n",
    "    acc_r  = np.mean(pred_r == y_test) * 100\n",
    "    history_rule.append(acc_r)\n",
    "    \n",
    "    # 2. ML Klasik (Logistic Regression)\n",
    "    m_ml = ClassicalLogisticRegression(lr=0.2, epochs=300)\n",
    "    m_ml.train(X_sub, y_sub)\n",
    "    pred_m = m_ml.predict(X_test)\n",
    "    acc_m  = np.mean(pred_m == y_test) * 100\n",
    "    history_ml.append(acc_m)\n",
    "    \n",
    "    # 3. Deep Learning (Mini-MLP)\n",
    "    m_dl = MiniDeepNeuralNetwork(input_dim=2, hidden_dim=8, lr=0.2, epochs=600)\n",
    "    m_dl.train(X_sub, y_sub)\n",
    "    pred_d = m_dl.predict(X_test)\n",
    "    acc_d  = np.mean(pred_d == y_test) * 100\n",
    "    history_dl.append(acc_d)\n",
    "\n",
    "# Menampilkan tabel rangkuman eksperimen\n",
    "print(\"Tabel Evaluasi Akurasi terhadap Skala Data Latih:\")\n",
    "print(f\"{'Jumlah Data (N)':<18} | {'Rule-Based (%)':<16} | {'ML Klasik (%)':<16} | {'Deep Learning (%)':<18}\")\n",
    "print(\"-\" * 75)\n",
    "for i, n in enumerate(sample_sizes):\n",
    "    print(f\"{n:<18} | {history_rule[i]:<16.2f} | {history_ml[i]:<16.2f} | {history_dl[i]:<18.2f}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Visualisasi Kurva Penskalaan & Batas Keputusan (*Decision Boundary*)\n",
    "Mari kita visualisasikan kurva penskalaan data dan bentuk batas keputusan yang dihasilkan oleh ketiga model:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. Plot Kurva Skalabilitas Data\n",
    "plt.figure(figsize=(10, 5), dpi=150)\n",
    "plt.plot(sample_sizes, history_rule, marker='s', label='Rule-Based AI (Konstan)', color='#7F8C8D', linestyle=':')\n",
    "plt.plot(sample_sizes, history_ml,   marker='o', label='Machine Learning Klasik (Jenuh/Plateau)', color='#2980B9', linewidth=2)\n",
    "plt.plot(sample_sizes, history_dl,   marker='^', label='Deep Learning (Terus Bertumbuh)', color='#C0392B', linewidth=2.5)\n",
    "\n",
    "plt.title('Kurva Empiris Skalabilitas Akurasi terhadap Volume Data Latih', fontsize=12, fontweight='bold', pad=12)\n",
    "plt.xlabel('Jumlah Sampel Data Latih (N)', fontsize=10)\n",
    "plt.ylabel('Akurasi pada Data Uji Independen (%)', fontsize=10)\n",
    "plt.grid(True, linestyle=':', alpha=0.6)\n",
    "plt.legend(fontsize=10)\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# 2. Plot Bidang Batas Keputusan (Decision Boundaries) pada Data Penuh (N=400)\n",
    "fig, axes = plt.subplots(1, 3, figsize=(16, 4.8), dpi=150)\n",
    "\n",
    "# Grid koordinat untuk kontur keputusan\n",
    "x1_mesh, x2_mesh = np.meshgrid(np.linspace(0.1, 0.9, 150), np.linspace(0.5, 8.0, 150))\n",
    "X_grid = np.column_stack([x1_mesh.ravel(), x2_mesh.ravel()])\n",
    "\n",
    "models = [('Rule-Based AI', m_rule), ('ML Klasik (Logistic Reg)', m_ml), ('Deep Learning (MLP)', m_dl)]\n",
    "\n",
    "for ax, (title, model) in zip(axes, models):\n",
    "    grid_pred = model.predict(X_grid).reshape(x1_mesh.shape)\n",
    "    # Render bidang warna daerah prediksi\n",
    "    ax.contourf(x1_mesh, x2_mesh, grid_pred, alpha=0.25, cmap='RdYlGn_r')\n",
    "    # Plot sebaran data uji riil\n",
    "    ax.scatter(X_test[y_test == 0, 0], X_test[y_test == 0, 1], color='#27AE60', s=35, label='Sehat (0)')\n",
    "    ax.scatter(X_test[y_test == 1, 0], X_test[y_test == 1, 1], color='#C0392B', s=35, label='Sakit (1)')\n",
    "    \n",
    "    ax.set_title(title, fontsize=11, fontweight='bold')\n",
    "    ax.set_xlabel('Rasio Kuning Daun')\n",
    "    ax.set_ylabel('Diameter Bercak (mm)')\n",
    "    ax.legend(fontsize=8, loc='upper left')\n",
    "    ax.grid(True, linestyle=':', alpha=0.5)\n",
    "\n",
    "plt.suptitle('Komparasi Geometris Bidang Batas Keputusan Ketiga Paradigma', fontsize=12, fontweight='bold', y=1.02)\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Pembahasan Penggunaan Kode 4:\n",
    "- **Panel 1 (Rule-Based)**: Batas keputusan berbentuk kotak kaku (*orthogonal rectangular boundary*). Ini adalah ciri khas percabangan `if-else`.\n",
    "- **Panel 2 (ML Klasik)**: Batas keputusan berbentuk garis lurus miring (*linear hyperplane*). Cepat dan stabil, namun gagal menangkap kelengkungan kurva alamiah data.\n",
    "- **Panel 3 (Deep Learning)**: Batas keputusan berbentuk kurva mulus yang meliuk fleksibel mengikuti kontur sebaran data non-linier berkat fungsi aktivasi ReLU dan lapisan tersembunyi."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Tugas Mandiri Pemrograman (Coding Challenge)\n",
    "\n",
    "### Skenario: Menambahkan Fitur Interaksi Non-Linier pada ML Klasik\n",
    "Sebelum beralih ke Deep Learning yang memakan daya komputasi tinggi, seorang insinyur cerdas dapat mencoba **Rekayasa Fitur Polinomial (*Polynomial Feature Engineering*)** pada model Machine Learning klasik.\n",
    "\n",
    "**Tugas Anda:**  \n",
    "1. Buat matriks fitur baru `X_poly` yang menambahkan fitur kuadratik: $[x_1, x_2, x_1^2, x_2^2, x_1 \\cdot x_2]$.  \n",
    "2. Latih model `ClassicalLogisticRegression` pada fitur baru tersebut dengan data latih $N=400$.  \n",
    "3. Amati apakah akurasi ML klasik yang awalnya jenuh mampu mendekati performa Deep Learning tanpa harus menggunakan jaringan syaraf bertingkat!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ======================================================================\n",
    "# TUGAS MAHASISWA: Lengkapi blok rekayasa fitur polinomial di bawah ini:\n",
    "# ======================================================================\n",
    "\n",
    "# 1. Ekstrak fitur individual dari data train dan test\n",
    "x1_tr = X_train_full[:, 0]\n",
    "x2_tr = X_train_full[:, 1]\n",
    "x1_te = X_test[:, 0]\n",
    "x2_te = X_test[:, 1]\n",
    "\n",
    "# 2. Bentuk matriks polinomial 5-dimensi: [x1, x2, x1^2, x2^2, x1*x2]\n",
    "X_train_poly = np.column_stack([\n",
    "    x1_tr, \n",
    "    x2_tr, \n",
    "    x1_tr ** 2, \n",
    "    x2_tr ** 2, \n",
    "    x1_tr * x2_tr\n",
    "])\n",
    "\n",
    "X_test_poly = np.column_stack([\n",
    "    x1_te, \n",
    "    x2_te, \n",
    "    x1_te ** 2, \n",
    "    x2_te ** 2, \n",
    "    x1_te * x2_te\n",
    "])\n",
    "\n",
    "# 3. Latih model Machine Learning Klasik pada fitur polinomial\n",
    "model_poly_ml = ClassicalLogisticRegression(lr=0.05, epochs=500)\n",
    "model_poly_ml.train(X_train_poly, y_train_full)\n",
    "\n",
    "# 4. Evaluasi hasil akurasi pada data uji\n",
    "pred_poly = model_poly_ml.predict(X_test_poly)\n",
    "acc_poly = np.mean(pred_poly == y_test) * 100\n",
    "\n",
    "print(f\"Akurasi ML Klasik Tanpa Rekayasa Fitur : {history_ml[-1]:.2f}%\")\n",
    "print(f\"Akurasi ML Klasik DENGAN Rekayasa Fitur: {acc_poly:.2f}%\")\n",
    "print(f\"Akurasi Deep Learning Otomatis        : {history_dl[-1]:.2f}%\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Rubrik Penilaian Praktikum Mandiri\n",
    "\n",
    "| Aspek Penilaian | Bobot | Kriteria Capaian |\n",
    "| :--- | :---: | :--- |\n",
    "| **Kerapihan Kode & Dokumentasi** | 20% | Mahasiswa menyertakan type-hints dan komentar penjelasan per baris kode. |\n",
    "| **Analisis Kurva Skalabilitas** | 40% | Mahasiswa mampu membaca titik potong (*crossover*) dan menjelaskan konsep *saturation plateau* pada sesi responsi. |\n",
    "| **Ketepatan Rekayasa Fitur** | 40% | Logika rekayasa fitur polinomial berjalan mulus dan membuktikan lonjakan akurasi ML klasik mendekati performa Deep Learning. |"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

with open("e:/Project Buku/notebooks/part-01/AI_Modul_1.3_Praktikum_Perbedaan_AI_ML_DL.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)

print("Notebook 1.3 successfully generated!")
